import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ActionButton, formStyles } from '../../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../../src/components/ui';
import { ARTIST_PROSPECT_ACTIONS_KEY, readArtistProspectActions, type ArtistProspectAction } from '../../src/utils/artistProspectActions';
import { ARTIST_PROSPECTS_KEY, readArtistProspects, type ArtistProspect } from '../../src/utils/artistProspects';
import { theme } from '../../src/theme';

type Choice = 'preserve' | 'reassign' | 'remove';
export default function ArtistProspectDelete() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const [prospects, setProspects] = useState<ArtistProspect[]>([]); const [actions, setActions] = useState<ArtistProspectAction[]>([]); const [choice, setChoice] = useState<Choice>('preserve'); const [target, setTarget] = useState(''); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(ARTIST_PROSPECTS_KEY), AsyncStorage.getItem(ARTIST_PROSPECT_ACTIONS_KEY)]).then(([prospectValue, actionValue]) => { setProspects(readArtistProspects(prospectValue)); setActions(readArtistProspectActions(actionValue)); }).catch(() => setError('Removal impact could not be reviewed on this device.')).finally(() => setReady(true)); }, []);
  const prospect = prospects.find(item => item.id === id); const linked = actions.filter(item => item.prospectId === id); const alternatives = prospects.filter(item => item.id !== id);
  async function confirm() { if (!prospect) return; if (choice === 'reassign' && !alternatives.some(item => item.id === target)) { setError('Choose another private prospect for the linked follow-ups.'); return; } setBusy(true); setError(null); const remaining = prospects.filter(item => item.id !== id); let nextActions = actions; if (choice === 'remove') nextActions = actions.filter(item => item.prospectId !== id); if (choice === 'reassign') { const destination = alternatives.find(item => item.id === target)!; nextActions = actions.map(item => item.prospectId === id ? { ...item, prospectId: destination.id, prospectName: destination.name, updatedAt: new Date().toISOString() } : item); } try { await AsyncStorage.multiSet([[ARTIST_PROSPECTS_KEY, JSON.stringify(remaining)], [ARTIST_PROSPECT_ACTIONS_KEY, JSON.stringify(nextActions)]]); router.replace('/artist-prospects'); } catch { setError('Removal failed. The private prospect and linked follow-ups were kept.'); } finally { setBusy(false); } }
  if (!ready) return <Screen><Body>Reviewing prospect removal impact…</Body></Screen>;
  if (!prospect) return <Screen><PageHeader eyebrow="PRIVATE PROSPECT REMOVAL" title="Prospect profile not found." description="The profile may already be removed or belong to another device." /><Button label="Manage private prospect profiles" href="/artist-prospects" secondary /><Footer /></Screen>;
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · REMOVAL IMPACT REVIEW" title={`Before removing ${prospect.name}`} description="Choose what happens to linked private follow-up history. This affects only device-local owner planning data." /><PreviewNotice /><Card title={`${linked.length} linked private ${linked.length === 1 ? 'follow-up' : 'follow-ups'}`} description={`${linked.filter(item => !item.completed).length} open · ${linked.filter(item => item.completed).length} completed. Review the choices below before removing the profile.`} />{linked.map(item => <View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.action}</Text><Body>{item.completed ? 'Completed' : 'Open'} · {item.priority} · {item.owner}</Body></View>)}
    <SectionHeader title="Linked follow-up decision" /><View accessibilityRole="radiogroup" accessibilityLabel="Linked follow-up decision" style={styles.grid}><Option label="Preserve as unlinked history" selected={choice === 'preserve'} onPress={() => setChoice('preserve')} /><Option label="Reassign to another prospect" selected={choice === 'reassign'} onPress={() => setChoice('reassign')} /><Option label="Remove linked follow-ups" selected={choice === 'remove'} onPress={() => setChoice('remove')} /></View>{choice === 'preserve' && <Card title="Preserve history" description="Follow-ups remain on this device with the removed prospect’s name, but no longer open a live prospect review." />}{choice === 'remove' && <Card title="Remove linked follow-ups" description="All linked open and completed follow-ups will be removed with this profile. A prior transfer backup is the only recovery path." />}{choice === 'reassign' && <><Text style={styles.cardTitle}>Choose destination prospect</Text><View accessibilityRole="radiogroup" accessibilityLabel="Prospect reassignment destination" style={styles.grid}>{alternatives.map(item => <Option key={item.id} label={item.name} selected={target === item.id} onPress={() => setTarget(item.id)} />)}</View>{!alternatives.length && <Card title="No other private prospect available" description="Create another profile before choosing reassignment, or preserve/remove the linked follow-ups." />}</>}<ActionButton label="Remove prospect with reviewed follow-up decision" disabled={busy} onPress={() => { void confirm(); }} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}<Button label="Cancel and keep private prospect" href="/artist-prospects" secondary /><Footer /></Screen>;
}
function Option({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
