import { expect, test, type Page } from '@playwright/test';

const prospectKey = '@ptown/artist-prospects/v1'; const actionKey = '@ptown/artist-prospect-actions/v1';
const source = { id: 'source', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: '', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' }; const destination = { ...source, id: 'destination', name: 'Sample Baker', track: 'Culinary' }; const linked = { id: 'linked', prospectId: source.id, prospectName: source.name, action: 'Review reel', owner: 'Owner', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T12:00:00.000Z' };
async function seed(page: Page) { await page.goto('/artist-prospects'); await page.evaluate(({ prospectKey, actionKey, prospects, actions }) => { localStorage.setItem(prospectKey, JSON.stringify(prospects)); localStorage.setItem(actionKey, JSON.stringify(actions)); }, { prospectKey, actionKey, prospects: [source, destination], actions: [linked] }); await page.goto('/artist-prospect-delete/source'); }

test('Prospect removal preserves linked follow-up history by default', async ({ page }) => { await seed(page); await expect(page.getByText('1 linked private follow-up', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Remove prospect with reviewed follow-up decision', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), prospectKey)).toEqual([destination]); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([linked]); });
test('Prospect removal can reassign linked follow-ups', async ({ page }) => { await seed(page); await page.getByRole('radio', { name: 'Reassign to another prospect', exact: true }).click(); await page.getByRole('radio', { name: destination.name, exact: true }).click(); await page.getByRole('button', { name: 'Remove prospect with reviewed follow-up decision', exact: true }).click(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey))[0]).toMatchObject({ prospectId: destination.id, prospectName: destination.name }); });
test('Prospect removal can delete follow-ups while cancel keeps both datasets', async ({ page }) => { await seed(page); await page.getByRole('link', { name: 'Cancel and keep private prospect →', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), prospectKey)).toEqual([source, destination]); await page.goto('/artist-prospect-delete/source'); await page.getByRole('radio', { name: 'Remove linked follow-ups', exact: true }).click(); await page.getByRole('button', { name: 'Remove prospect with reviewed follow-up decision', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([]); });
