import { expect, test } from '@playwright/test';

const prospectKey = '@ptown/artist-prospects/v1'; const actionKey = '@ptown/artist-prospect-actions/v1';
const prospect = { id: 'prospect-one', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: '', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' };

test('Prospect review prefills a private owner follow-up and retains completion state', async ({ page }) => {
  await page.goto('/artist-prospects'); await page.evaluate(({ prospectKey, prospect }) => localStorage.setItem(prospectKey, JSON.stringify([prospect])), { prospectKey, prospect }); await page.goto('/artist-prospects/prospect-one'); await page.getByRole('link', { name: 'Create or manage follow-ups for River Producer →', exact: true }).click(); await expect(page).toHaveURL('/artist-prospect-actions?prospect=prospect-one'); await expect(page.getByRole('radio', { name: 'River Producer', exact: true })).toBeChecked(); await expect(page.getByRole('textbox', { name: 'Follow-up action', exact: true })).toHaveValue(/Owner review may decide/); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await expect(page.getByText(/No person was assigned, contacted, or notified/)).toBeVisible(); await page.getByRole('button', { name: 'Mark private prospect follow-up complete', exact: true }).click(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey))[0].completed).toBe(true);
});

test('Prospect follow-up validation and removal preserve device-only behavior', async ({ page }) => {
  await page.goto('/artist-prospect-actions'); await page.evaluate(({ prospectKey, prospect }) => localStorage.setItem(prospectKey, JSON.stringify([prospect])), { prospectKey, prospect }); await page.reload(); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Choose a private prospect'); await page.getByRole('radio', { name: 'River Producer', exact: true }).click(); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await page.getByRole('button', { name: 'Remove private prospect follow-up', exact: true }).click(); await expect(page.getByText('No private prospect follow-ups', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([]);
});
