import { expect, test } from '@playwright/test';

const key = '@ptown/artist-prospects/v1';
test('Artist Development creates, edits, and removes a private prospect profile', async ({ page }) => {
  await page.goto('/artist-development'); await page.getByRole('link', { name: 'Manage private prospect profiles →', exact: true }).click(); await expect(page).toHaveURL('/artist-prospects'); await page.getByRole('button', { name: 'Save private prospect profile', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Enter an artist'); await page.getByRole('textbox', { name: 'Artist, creative, group, or project name', exact: true }).fill('River City Ensemble'); await page.getByRole('radiogroup', { name: 'Prospect development track', exact: true }).getByRole('radio', { name: 'Production', exact: true }).click(); await page.getByRole('textbox', { name: 'Home market or region', exact: true }).fill('Paducah, Kentucky'); await page.getByRole('textbox', { name: 'Portfolio or work reference', exact: true }).fill('Public rehearsal reel'); await page.getByRole('textbox', { name: 'Availability or timing', exact: true }).fill('Fall follow-up'); await page.getByRole('radiogroup', { name: 'Prospect planning status', exact: true }).getByRole('radio', { name: 'Ready for owner review', exact: true }).click(); await page.getByRole('button', { name: 'Save private prospect profile', exact: true }).click(); await expect(page.getByText('READY FOR OWNER REVIEW · PRODUCTION', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)).toHaveLength(1);
  await page.getByRole('button', { name: 'Edit River City Ensemble', exact: true }).click(); await page.getByRole('textbox', { name: 'Availability or timing', exact: true }).fill('Winter follow-up'); await page.getByRole('button', { name: 'Update private prospect profile', exact: true }).click(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key))[0].availability).toBe('Winter follow-up'); await page.getByRole('link', { name: 'Review removal of River City Ensemble →', exact: true }).click(); await page.getByRole('button', { name: 'Remove prospect with reviewed follow-up decision', exact: true }).click(); await expect(page).toHaveURL('/artist-prospects'); await expect(page.getByText('No private prospect profiles', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)).toEqual([]);
});

test('Prospect profiles surface missing booking-readiness details and stay device-local', async ({ page }) => {
  const prospect = { id: 'prospect-one', name: 'Sample Vocalist', track: 'Performance', market: '', portfolio: '', availability: '', notes: 'Public discovery only', status: 'New lead', updatedAt: '2026-09-20T12:00:00.000Z' }; await page.goto('/artist-prospects'); await page.evaluate(({ key, prospect }) => localStorage.setItem(key, JSON.stringify([prospect])), { key, prospect }); await page.reload(); await expect(page.getByText('NEEDS PLANNING DETAILS · PERFORMANCE', { exact: true })).toBeVisible(); await expect(page.getByText(/Missing: home market, portfolio or work reference, availability or timing/)).toBeVisible(); await expect(page.getByText(/does not submit an application, contact anyone, promise a booking/)).toBeVisible();
});

test('Prospect filters narrow the private list and reset cleanly', async ({ page }) => {
  const prospects = [{ id: 'ready-one', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: 'Strong live work', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' }, { id: 'needs-one', name: 'Sample Baker', track: 'Culinary', market: '', portfolio: '', availability: '', notes: '', status: 'Needs materials', updatedAt: '2026-09-20T12:00:00.000Z' }]; await page.goto('/artist-prospects'); await page.evaluate(({ key, prospects }) => localStorage.setItem(key, JSON.stringify(prospects)), { key, prospects }); await page.reload(); await page.getByRole('radio', { name: 'Production', exact: true }).last().click(); await expect(page.getByText('1 of 2 private prospects shown', { exact: true })).toBeVisible(); await expect(page.getByText('River Producer', { exact: true })).toBeVisible(); await expect(page.getByText('Sample Baker', { exact: true })).toHaveCount(0); await page.getByRole('button', { name: 'Reset prospect filters', exact: true }).click(); await expect(page.getByText('2 of 2 private prospects shown', { exact: true })).toBeVisible();
});

test('Private prospect review shows readiness and a copyable owner summary', async ({ page }) => {
  const prospect = { id: 'review-one', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: 'Strong live work', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' }; await page.goto('/artist-prospects'); await page.evaluate(({ key, prospect }) => localStorage.setItem(key, JSON.stringify([prospect])), { key, prospect }); await page.goto('/artist-prospects/review-one'); await expect(page.getByText('Planning details complete', { exact: true })).toBeVisible(); await expect(page.getByText('Owner review may decide whether a separate, authorized outreach plan should be prepared. No contact has been sent.', { exact: true })).toBeVisible(); const summary = await page.getByRole('textbox', { name: 'Private prospect review summary', exact: true }).inputValue(); expect(summary).toContain('Prospect: River Producer'); expect(summary).toContain('Not submitted, contacted, booked, promised, or enrolled.');
});
