import { expect, test } from '@playwright/test';

const prospectKey = '@ptown/artist-prospects/v1'; const actionKey = '@ptown/artist-prospect-actions/v1';
const prospect = { id: 'current', name: 'Sample Baker', track: 'Culinary', market: 'Paducah', portfolio: 'Menu', availability: 'Fall', notes: '', status: 'New lead', updatedAt: '2026-09-20T12:00:00.000Z' }; const unlinked = { id: 'unlinked', prospectId: 'removed', prospectName: 'River Producer', action: 'Review reel', owner: 'Owner', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T12:00:00.000Z' };
test.beforeEach(async ({ page }) => { await page.goto('/artist-prospect-actions'); await page.evaluate(({ prospectKey, actionKey, prospect, unlinked }) => { localStorage.setItem(prospectKey, JSON.stringify([prospect])); localStorage.setItem(actionKey, JSON.stringify([unlinked])); }, { prospectKey, actionKey, prospect, unlinked }); });

test('Follow-up queue surfaces unlinked history and retains it deliberately', async ({ page }) => { await page.reload(); await expect(page.getByText('Unlinked history', { exact: true })).toBeVisible(); await page.getByRole('link', { name: 'Review 1 unlinked follow-up →', exact: true }).click(); await page.getByRole('button', { name: 'Keep Review reel as unlinked history', exact: true }).click(); await expect(page.getByText(/remains preserved as unlinked private history/)).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([unlinked]); });
test('Unlinked prospect follow-up reconnects to a current profile', async ({ page }) => { await page.goto('/artist-prospect-actions-unlinked'); await page.getByRole('radio', { name: prospect.name, exact: true }).click(); await page.getByRole('button', { name: 'Reconnect Review reel', exact: true }).click(); await expect(page.getByText('No unlinked private follow-ups', { exact: true })).toBeVisible(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey))[0]).toMatchObject({ prospectId: prospect.id, prospectName: prospect.name }); });
test('Unlinked prospect follow-up can be removed from private history', async ({ page }) => { await page.goto('/artist-prospect-actions-unlinked'); await page.getByRole('button', { name: 'Remove Review reel from private history', exact: true }).click(); await expect(page.getByText('No unlinked private follow-ups', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([]); });
