import { expect, test } from '@playwright/test';

const prospectKey = '@ptown/artist-prospects/v1'; const actionKey = '@ptown/artist-prospect-actions/v1';
const prospect = { id: 'prospect-one', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: '', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' };

test('Prospect review prefills a private owner follow-up and retains completion state', async ({ page }) => {
  await page.goto('/artist-prospects'); await page.evaluate(({ prospectKey, prospect }) => localStorage.setItem(prospectKey, JSON.stringify([prospect])), { prospectKey, prospect }); await page.goto('/artist-prospects/prospect-one'); await page.getByRole('link', { name: 'Create or manage follow-ups for River Producer →', exact: true }).click(); await expect(page).toHaveURL('/artist-prospect-actions?prospect=prospect-one'); await expect(page.getByRole('radio', { name: 'River Producer', exact: true })).toBeChecked(); await expect(page.getByRole('textbox', { name: 'Follow-up action', exact: true })).toHaveValue(/Owner review may decide/); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await expect(page.getByText(/No person was assigned, contacted, or notified/)).toBeVisible(); await page.getByRole('button', { name: 'Mark private prospect follow-up complete', exact: true }).click(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey))[0].completed).toBe(true);
});

test('Prospect follow-up validation and removal preserve device-only behavior', async ({ page }) => {
  await page.goto('/artist-prospect-actions'); await page.evaluate(({ prospectKey, prospect }) => localStorage.setItem(prospectKey, JSON.stringify([prospect])), { prospectKey, prospect }); await page.reload(); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Choose a private prospect'); await page.getByRole('radio', { name: 'River Producer', exact: true }).click(); await page.getByRole('button', { name: 'Save private prospect follow-up', exact: true }).click(); await page.getByRole('button', { name: 'Remove private prospect follow-up', exact: true }).click(); await expect(page.getByText('No private prospect follow-ups', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([]);
});

test('Prospect review shows linked open and completed follow-up history', async ({ page }) => {
  const actions = [{ id: 'open-action', prospectId: prospect.id, prospectName: prospect.name, action: 'Review public reel', owner: 'Owner', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T12:00:00.000Z' }, { id: 'done-action', prospectId: prospect.id, prospectName: prospect.name, action: 'Confirm market', owner: 'Program Director', priority: 'Normal', dueDate: '', completed: true, updatedAt: '2026-09-20T12:00:00.000Z' }]; await page.goto('/artist-prospects'); await page.evaluate(({ prospectKey, actionKey, prospect, actions }) => { localStorage.setItem(prospectKey, JSON.stringify([prospect])); localStorage.setItem(actionKey, JSON.stringify(actions)); }, { prospectKey, actionKey, prospect, actions }); await page.goto('/artist-prospects/prospect-one'); await expect(page.getByText('1 open · 1 completed', { exact: true })).toBeVisible(); await expect(page.getByText('Review public reel', { exact: true })).toBeVisible(); await expect(page.getByText('Confirm market', { exact: true })).toBeVisible();
});

test('Prospect follow-up queue filters by linked prospect, completion, priority, and owner role', async ({ page }) => {
  const other = { ...prospect, id: 'prospect-two', name: 'Sample Baker', track: 'Culinary' }; const actions = [{ id: 'one', prospectId: prospect.id, prospectName: prospect.name, action: 'Review public reel', owner: 'Owner', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T12:00:00.000Z' }, { id: 'two', prospectId: other.id, prospectName: other.name, action: 'Request menu', owner: 'Culinary Director', priority: 'Normal', dueDate: '', completed: true, updatedAt: '2026-09-20T12:00:00.000Z' }]; await page.goto('/artist-prospect-actions'); await page.evaluate(({ prospectKey, actionKey, prospects, actions }) => { localStorage.setItem(prospectKey, JSON.stringify(prospects)); localStorage.setItem(actionKey, JSON.stringify(actions)); }, { prospectKey, actionKey, prospects: [prospect, other], actions }); await page.reload(); await page.getByRole('radio', { name: 'Completed', exact: true }).click(); await page.getByRole('radio', { name: 'Normal', exact: true }).last().click(); await page.getByRole('textbox', { name: 'Responsible owner role contains', exact: true }).fill('culinary'); await expect(page.getByText('1 of 2 private follow-ups shown', { exact: true })).toBeVisible(); await expect(page.getByText('Request menu', { exact: true })).toBeVisible(); await expect(page.getByText('Review public reel', { exact: true })).toHaveCount(0); await page.getByRole('button', { name: 'Reset prospect follow-up filters', exact: true }).click(); await expect(page.getByText('1 of 2 private follow-ups shown', { exact: true })).toBeVisible();
});
