import { expect, test } from '@playwright/test';

const prospectKey = '@ptown/artist-prospects/v1'; const actionKey = '@ptown/artist-prospect-actions/v1';
const prospect = { id: 'prospect-one', name: 'River Producer', track: 'Production', market: 'Paducah', portfolio: 'Public reel', availability: 'October', notes: '', status: 'Ready for owner review', updatedAt: '2026-09-20T12:00:00.000Z' };
const action = { id: 'action-one', prospectId: prospect.id, prospectName: prospect.name, action: 'Review reel', owner: 'Owner', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T12:00:00.000Z' };

test('Private Artist Development transfer moves prospects and follow-ups together', async ({ browser, page }) => {
  await page.goto('/artist-prospect-backup'); await page.evaluate(({ prospectKey, actionKey, prospect, action }) => { localStorage.setItem(prospectKey, JSON.stringify([prospect])); localStorage.setItem(actionKey, JSON.stringify([action])); }, { prospectKey, actionKey, prospect, action }); await page.reload(); const code = await page.getByRole('textbox', { name: 'Private Artist Development transfer code', exact: true }).inputValue(); expect(JSON.parse(code)).toMatchObject({ type: 'artist-prospect-bundle', prospects: [prospect], actions: [action] });
  const context = await browser.newContext(); try { const other = await context.newPage(); await other.goto('/artist-prospect-backup'); await other.getByRole('textbox', { name: 'Paste private Artist Development transfer code', exact: true }).fill(code); await other.getByRole('button', { name: 'Review private Artist Development transfer', exact: true }).click(); await expect(other.getByText(/1 linked · 0 unlinked history/)).toBeVisible(); expect(await other.evaluate(key => localStorage.getItem(key), prospectKey)).toBeNull(); await other.getByRole('button', { name: 'Replace private prospects and follow-ups together', exact: true }).click(); expect(await other.evaluate(key => JSON.parse(localStorage.getItem(key)!), prospectKey)).toEqual([prospect]); expect(await other.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([action]); } finally { await context.close(); }
});

test('Artist Development transfer rejects invalid data and cancel preserves current device data', async ({ page }) => {
  await page.goto('/artist-prospect-backup'); await page.evaluate(({ prospectKey, actionKey, prospect, action }) => { localStorage.setItem(prospectKey, JSON.stringify([prospect])); localStorage.setItem(actionKey, JSON.stringify([action])); }, { prospectKey, actionKey, prospect, action }); await page.reload(); const input = page.getByRole('textbox', { name: 'Paste private Artist Development transfer code', exact: true }); await input.fill(JSON.stringify({ app: 'PTown Access', type: 'artist-prospect-bundle', format: 1, prospects: [prospect], actions: [{ ...action, priority: 'Urgent' }] })); await page.getByRole('button', { name: 'Review private Artist Development transfer', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('could not be read'); const code = await page.getByRole('textbox', { name: 'Private Artist Development transfer code', exact: true }).inputValue(); await input.fill(code); await page.getByRole('button', { name: 'Review private Artist Development transfer', exact: true }).click(); await page.getByRole('button', { name: 'Cancel Artist Development replacement', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), prospectKey)).toEqual([prospect]);
});
