import { expect, test } from '@playwright/test';

const key = '@ptown/artist-prospects/v1';
test('Artist Development creates, edits, and removes a private prospect profile', async ({ page }) => {
  await page.goto('/artist-development'); await page.getByRole('link', { name: 'Manage private prospect profiles →', exact: true }).click(); await expect(page).toHaveURL('/artist-prospects'); await page.getByRole('button', { name: 'Save private prospect profile', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Enter an artist'); await page.getByRole('textbox', { name: 'Artist, creative, group, or project name', exact: true }).fill('River City Ensemble'); await page.getByRole('radio', { name: 'Production', exact: true }).click(); await page.getByRole('textbox', { name: 'Home market or region', exact: true }).fill('Paducah, Kentucky'); await page.getByRole('textbox', { name: 'Portfolio or work reference', exact: true }).fill('Public rehearsal reel'); await page.getByRole('textbox', { name: 'Availability or timing', exact: true }).fill('Fall follow-up'); await page.getByRole('radio', { name: 'Ready for owner review', exact: true }).click(); await page.getByRole('button', { name: 'Save private prospect profile', exact: true }).click(); await expect(page.getByText('READY FOR OWNER REVIEW · PRODUCTION', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)).toHaveLength(1);
  await page.getByRole('button', { name: 'Edit River City Ensemble', exact: true }).click(); await page.getByRole('textbox', { name: 'Availability or timing', exact: true }).fill('Winter follow-up'); await page.getByRole('button', { name: 'Update private prospect profile', exact: true }).click(); expect((await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key))[0].availability).toBe('Winter follow-up'); await page.getByRole('button', { name: 'Remove River City Ensemble', exact: true }).click(); await expect(page.getByText('No private prospect profiles', { exact: true })).toBeVisible(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)).toEqual([]);
});

test('Prospect profiles surface missing booking-readiness details and stay device-local', async ({ page }) => {
  const prospect = { id: 'prospect-one', name: 'Sample Vocalist', track: 'Performance', market: '', portfolio: '', availability: '', notes: 'Public discovery only', status: 'New lead', updatedAt: '2026-09-20T12:00:00.000Z' }; await page.goto('/artist-prospects'); await page.evaluate(({ key, prospect }) => localStorage.setItem(key, JSON.stringify([prospect])), { key, prospect }); await page.reload(); await expect(page.getByText('NEEDS PLANNING DETAILS · PERFORMANCE', { exact: true })).toBeVisible(); await expect(page.getByText(/Missing: home market, portfolio or work reference, availability or timing/)).toBeVisible(); await expect(page.getByText(/does not submit an application, contact anyone, promise a booking/)).toBeVisible();
});
