import { expect, test } from '@playwright/test';

const draftKey = '@ptown/media-drafts/v1'; const actionKey = '@ptown/media-actions/v1';
const draft = { id: 'history-draft', title: 'Opening coverage', division: 'News & Editorial', owner: 'Journal editor', status: 'Assigned', deadline: '', notes: '', updatedAt: '2026-09-20T12:00:00.000Z' };
const actions = [
  { id: 'open', draftId: 'history-draft', draftTitle: 'Opening coverage', action: 'Confirm sources', owner: 'Journal editor', priority: 'High', dueDate: '2000-01-01', completed: false, updatedAt: '2026-09-20T00:00:00.000Z' },
  { id: 'done', draftId: 'history-draft', draftTitle: 'Opening coverage', action: 'Create assignment', owner: 'Media Director', priority: 'Normal', dueDate: '', completed: true, updatedAt: '2026-09-20T00:00:00.000Z' },
  { id: 'other', draftId: 'other-draft', draftTitle: 'Other project', action: 'Other action', owner: 'Producer', priority: 'Low', dueDate: '', completed: false, updatedAt: '2026-09-20T00:00:00.000Z' },
];
test('Private draft review shows only its linked open and completed action history', async ({ page }) => { await page.goto('/media-drafts'); await page.evaluate(({ draftKey, actionKey, draft, actions }) => { localStorage.setItem(draftKey, JSON.stringify([draft])); localStorage.setItem(actionKey, JSON.stringify(actions)); }, { draftKey, actionKey, draft, actions }); await page.goto('/media-drafts/history-draft'); await expect(page.getByText('1 open · 1 completed', { exact: true })).toBeVisible(); await expect(page.getByText('Confirm sources', { exact: true })).toBeVisible(); await expect(page.getByText('Create assignment', { exact: true })).toBeVisible(); await expect(page.getByText('Other action', { exact: true })).toHaveCount(0); });
test('Linked action management opens a draft-focused queue', async ({ page }) => { await page.goto('/media-drafts'); await page.evaluate(({ draftKey, actionKey, draft, actions }) => { localStorage.setItem(draftKey, JSON.stringify([draft])); localStorage.setItem(actionKey, JSON.stringify(actions)); }, { draftKey, actionKey, draft, actions }); await page.goto('/media-drafts/history-draft'); await page.getByRole('link', { name: 'Create or manage linked actions →', exact: true }).click(); await expect(page).toHaveURL('/media-actions?draft=history-draft&focus=history-draft'); await expect(page.getByRole('radio', { name: 'Opening coverage', exact: true }).first()).toBeChecked(); await expect(page.getByText('Other action', { exact: true })).toHaveCount(0); });
