import { expect, test } from '@playwright/test';

const draftKey = '@ptown/media-drafts/v1'; const actionKey = '@ptown/media-actions/v1';
const draft = { id: 'bundle-draft', title: 'Opening coverage', division: 'News & Editorial', owner: 'Journal editor', status: 'Assigned', deadline: '', notes: '', updatedAt: '2026-09-20T12:00:00.000Z' };
const action = { id: 'bundle-action', draftId: draft.id, draftTitle: draft.title, action: 'Confirm sources', owner: 'Journal editor', priority: 'High', dueDate: '', completed: false, updatedAt: '2026-09-20T00:00:00.000Z' };

test('Unified transfer moves linked drafts and actions between devices', async ({ browser, page }) => {
  await page.goto('/media-bundle-backup'); await page.evaluate(({ draftKey, actionKey, draft, action }) => { localStorage.setItem(draftKey, JSON.stringify([draft])); localStorage.setItem(actionKey, JSON.stringify([action])); }, { draftKey, actionKey, draft, action }); await page.reload(); const code = await page.getByRole('textbox', { name: 'Unified Media Group transfer code', exact: true }).inputValue(); expect(JSON.parse(code)).toMatchObject({ type: 'media-group-bundle', drafts: [draft], actions: [action] });
  const context = await browser.newContext(); try { const other = await context.newPage(); await other.goto('/media-bundle-backup'); await other.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }).fill(code); await other.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click(); await expect(other.getByText(/1 linked · 0 unlinked history/)).toBeVisible(); expect(await other.evaluate(key => localStorage.getItem(key), draftKey)).toBeNull(); await other.getByRole('button', { name: 'Replace private drafts and actions together', exact: true }).click(); expect(await other.evaluate(key => JSON.parse(localStorage.getItem(key)!), draftKey)).toEqual([draft]); expect(await other.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([action]); } finally { await context.close(); }
});

test('Unified transfer review rejects invalid data and cancel keeps current data', async ({ page }) => {
  await page.goto('/media-bundle-backup'); await page.evaluate(({ draftKey, actionKey, draft, action }) => { localStorage.setItem(draftKey, JSON.stringify([draft])); localStorage.setItem(actionKey, JSON.stringify([action])); }, { draftKey, actionKey, draft, action }); await page.reload(); const input = page.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }); await input.fill(JSON.stringify({ app: 'PTown Access', type: 'media-group-bundle', format: 1, drafts: [draft], actions: [{ ...action, priority: 'Urgent' }] })); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('could not be read');
  const code = await page.getByRole('textbox', { name: 'Unified Media Group transfer code', exact: true }).inputValue(); await input.fill(code); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click(); await page.getByRole('button', { name: 'Cancel unified replacement', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), draftKey)).toEqual([draft]); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([action]);
});

test('Unified transfer integrity report identifies relationship problems before replacement', async ({ page }) => {
  const duplicate = { ...draft, id: 'duplicate-draft', title: ' opening coverage ' }; const orphan = { ...action, id: 'orphan-action', draftId: 'missing-draft', draftTitle: 'Removed project', action: 'Archive notes' }; const mismatch = { ...action, id: 'mismatch-action', draftTitle: 'Old opening title', action: 'Confirm assignment' };
  await page.goto('/media-bundle-backup'); const input = page.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }); await input.fill(JSON.stringify({ app: 'PTown Access', type: 'media-group-bundle', format: 1, drafts: [draft, duplicate], actions: [orphan, mismatch] })); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click();
  await expect(page.getByText('3 of 3 integrity findings unresolved', { exact: true })).toBeVisible(); await expect(page.getByText(/Duplicate draft title:/)).toBeVisible(); await expect(page.getByText('Unlinked action: Archive notes', { exact: true })).toBeVisible(); await expect(page.getByText('Draft title mismatch: Confirm assignment', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Resolve 3 integrity findings before replacement', exact: true })).toBeDisabled(); expect(await page.evaluate(key => localStorage.getItem(key), draftKey)).toBeNull();
});

test('Incoming relationship repairs unlock reviewed replacement', async ({ page }) => {
  const orphan = { ...action, id: 'orphan-action', draftId: 'missing-draft', draftTitle: 'Removed project', action: 'Archive notes' }; const mismatch = { ...action, id: 'mismatch-action', draftTitle: 'Old opening title', action: 'Confirm assignment' };
  await page.goto('/media-bundle-backup'); await page.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }).fill(JSON.stringify({ app: 'PTown Access', type: 'media-group-bundle', format: 1, drafts: [draft], actions: [orphan, mismatch] })); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click();
  await page.getByRole('button', { name: 'Update stored title for Confirm assignment', exact: true }).click(); await page.getByRole('radio', { name: draft.title, exact: true }).click(); await page.getByRole('button', { name: 'Reconnect Archive notes', exact: true }).click(); await expect(page.getByText('No relationship issues found', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Replace private drafts and actions together', exact: true }).click();
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey); expect(saved).toHaveLength(2); expect(saved).toEqual(expect.arrayContaining([expect.objectContaining({ id: orphan.id, draftId: draft.id, draftTitle: draft.title }), expect.objectContaining({ id: mismatch.id, draftTitle: draft.title })]));
});

test('Explicitly retained unlinked history permits replacement', async ({ page }) => {
  const orphan = { ...action, id: 'orphan-action', draftId: 'missing-draft', draftTitle: 'Removed project', action: 'Archive notes' }; await page.goto('/media-bundle-backup'); await page.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }).fill(JSON.stringify({ app: 'PTown Access', type: 'media-group-bundle', format: 1, drafts: [draft], actions: [orphan] })); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click(); await page.getByRole('button', { name: 'Retain Archive notes as unlinked history', exact: true }).click(); await expect(page.getByText('Reviewed and retained for this replacement.', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Replace private drafts and actions together', exact: true }).click(); expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), actionKey)).toEqual([orphan]); const receipt = await page.getByRole('textbox', { name: 'Private transfer receipt', exact: true }).inputValue(); expect(receipt).toContain('Private drafts replaced: 1'); expect(receipt).toContain('Unlinked history retained: 1'); expect(receipt).toContain('Initial integrity findings: 1'); expect(receipt).toContain('Retained “Archive notes” as unlinked private history.');
});

test('Clean replacement receipt records that no repairs were needed', async ({ page }) => {
  await page.goto('/media-bundle-backup'); await page.getByRole('textbox', { name: 'Paste unified Media Group transfer code', exact: true }).fill(JSON.stringify({ app: 'PTown Access', type: 'media-group-bundle', format: 1, drafts: [draft], actions: [action] })); await page.getByRole('button', { name: 'Review unified Media Group transfer', exact: true }).click(); await page.getByRole('button', { name: 'Replace private drafts and actions together', exact: true }).click(); const receipt = await page.getByRole('textbox', { name: 'Private transfer receipt', exact: true }).inputValue(); expect(receipt).toContain('Linked actions: 1'); expect(receipt).toContain('Initial integrity findings: 0'); expect(receipt).toContain('No repairs or retention decisions were needed.');
});
