import { expect, test } from '@playwright/test';

const key = '@ptown/media-actions/v1';
const actions = [
  { id: 'overdue', draftId: 'a', draftTitle: 'Coverage', action: 'Confirm releases', owner: 'Media Director', priority: 'High', dueDate: '2000-01-01', completed: false, updatedAt: '2026-09-20T00:00:00.000Z' },
  { id: 'done', draftId: 'b', draftTitle: 'Podcast', action: 'Review rundown', owner: 'Program Director', priority: 'Normal', dueDate: '', completed: true, updatedAt: '2026-09-20T00:00:00.000Z' },
];
test('Action queue reports overdue work and preserves shareable filters', async ({ page }) => { await page.goto('/media-actions'); await page.evaluate(({ key, actions }) => localStorage.setItem(key, JSON.stringify(actions)), { key, actions }); await page.reload(); await expect(page.getByText('OVERDUE', { exact: true })).toBeVisible(); await page.getByRole('radio', { name: 'Completed', exact: true }).click(); await expect(page).toHaveURL('/media-actions?view=Completed'); await expect(page.getByText('Review rundown', { exact: true })).toBeVisible(); await expect(page.getByText('Confirm releases', { exact: true })).toHaveCount(0); });
test('Private actions transfer only after review and replacement', async ({ page, browser }) => { await page.goto('/media-actions'); await page.evaluate(({ key, actions }) => localStorage.setItem(key, JSON.stringify(actions)), { key, actions }); await page.goto('/media-action-backup'); const code = await page.getByRole('textbox', { name: 'Private action transfer code', exact: true }).inputValue(); const other = await browser.newContext({ baseURL: new URL(page.url()).origin }); try { const target = await other.newPage(); await target.goto('/media-action-backup'); await target.getByRole('textbox', { name: 'Paste private action transfer code', exact: true }).fill(code); await target.getByRole('button', { name: 'Review private action transfer', exact: true }).click(); await expect(target.getByText('Confirm releases', { exact: true })).toBeVisible(); expect(await target.evaluate(key => localStorage.getItem(key), key)).toBeNull(); await target.getByRole('button', { name: 'Replace this device’s private actions', exact: true }).click(); expect((await target.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)).length).toBe(2); } finally { await other.close(); } });
