import AsyncStorage from '@react-native-async-storage/async-storage';
import { Stack, useLocalSearchParams } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import { ActionButton, Feedback, Field, formStyles } from '../../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../../src/components/ui';
import { mediaTemplates } from '../../src/data/mediaTemplates';
import { MEDIA_DRAFTS_KEY, readMediaDrafts, type MediaDraft, type MediaWorkbookEntry } from '../../src/utils/mediaDrafts';
import { theme } from '../../src/theme';

const stageIds = ['assignment-brief', 'rights-checklist', 'approval-record', 'archive-handoff'];
const stages = mediaTemplates.filter(template => stageIds.includes(template.id));
export default function MediaDraftWorkbook() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [draft, setDraft] = useState<MediaDraft | null>(null); const [stage, setStage] = useState(stageIds[0]); const [entry, setEntry] = useState<MediaWorkbookEntry>({ checks: [], notes: '' }); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(MEDIA_DRAFTS_KEY).then(value => { const all = readMediaDrafts(value); const found = all.find(item => item.id === id) ?? null; setDrafts(all); setDraft(found); setEntry(found?.workbook?.[stageIds[0]] ?? { checks: [], notes: '' }); }).catch(() => setError('This device’s private workbook could not be read.')).finally(() => setReady(true)); }, [id]);
  function choose(next: string) { setStage(next); setEntry(draft?.workbook?.[next] ?? { checks: [], notes: '' }); setMessage(null); setError(null); }
  async function save() { if (!draft) return; setBusy(true); setMessage(null); setError(null); const nextDraft = { ...draft, workbook: { ...draft.workbook, [stage]: { checks: entry.checks, notes: entry.notes.trim() } }, updatedAt: new Date().toISOString() }; const next = drafts.map(item => item.id === draft.id ? nextDraft : item); try { await AsyncStorage.setItem(MEDIA_DRAFTS_KEY, JSON.stringify(next)); setDrafts(next); setDraft(nextDraft); setEntry(nextDraft.workbook[stage]); setMessage('Private workbook stage saved on this device. No approval or submission was created.'); } catch { setError('Workbook progress could not be saved. Existing draft data was kept.'); } finally { setBusy(false); } }
  if (!ready) return <Screen><Body>Loading private production workbook…</Body></Screen>;
  if (!draft) return <Screen><PageHeader eyebrow="PRIVATE PRODUCTION WORKBOOK" title="Draft not found." description="This workbook belongs to a private device draft that is unavailable here." /><Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer /></Screen>;
  const template = stages.find(item => item.id === stage)!; const complete = stages.reduce((total, item) => total + (draft.workbook?.[item.id]?.checks.length ?? 0), 0); const possible = stages.reduce((total, item) => total + item.checks.length, 0);
  return <Screen><Stack.Screen options={{ title: `${draft.title} workbook` }} /><PageHeader eyebrow="PTOWN MEDIA GROUP · PRIVATE WORKBOOK" title={draft.title} description="Keep assignment, rights, approval, and archive preparation together with this private device draft." /><PreviewNotice /><Card title={`${complete} of ${possible} workbook checks marked`} description="Progress is a planning aid only. A checked item is not proof, authorization, a signed release, a license, official approval, or archive verification." />
    <SectionHeader title="Workbook stage" /><View accessibilityRole="tablist" accessibilityLabel="Workbook stages" style={styles.grid}>{stages.map(item => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: stage === item.id }} onPress={() => choose(item.id)} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: stage === item.id ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: stage === item.id ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{item.title}</Text></Pressable>)}</View>
    <Card title={template.title} description={template.purpose} /><View style={styles.card}>{template.checks.map(check => { const selected = entry.checks.includes(check); return <Pressable key={check} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => { setEntry(current => ({ ...current, checks: selected ? current.checks.filter(item => item !== check) : [...current.checks, check] })); setMessage(null); }} style={{ minHeight: 48, flexDirection: 'row', gap: 12, alignItems: 'center' }}><Text style={{ color: theme.colors.gold, fontSize: 20 }}>{selected ? '☑' : '☐'}</Text><Body>{check}</Body></Pressable>; })}</View>
    <Field label={`${template.title} workbook notes`} value={entry.notes} onChangeText={value => { setEntry(current => ({ ...current, notes: value.slice(0, 1000) })); setMessage(null); }} placeholder="Record what must be verified, located, decided, or completed" multiline style={{ minHeight: 130, textAlignVertical: 'top' }} /><ActionButton label="Save private workbook stage" disabled={busy} onPress={() => { void save(); }} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    <Button label="Review this private draft" href={{ pathname: '/media-drafts/[id]', params: { id: draft.id } }} secondary /><Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer />
  </Screen>;
}
