import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Platform, Pressable, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { ARTIST_PROSPECT_ACTIONS_KEY, prospectActionTiming, readArtistProspectActions, type ArtistProspectAction, type ArtistProspectActionPriority } from '../src/utils/artistProspectActions';
import { ARTIST_PROSPECTS_KEY, artistProspectNextStep, readArtistProspects, type ArtistProspect } from '../src/utils/artistProspects';
import { theme } from '../src/theme';

const priorities: ArtistProspectActionPriority[] = ['High', 'Normal', 'Low'];
export default function ArtistProspectActions() {
  const params = useLocalSearchParams<{ prospect?: string | string[] }>(); const routeProspect = Array.isArray(params.prospect) ? params.prospect[0] : params.prospect; const [prospects, setProspects] = useState<ArtistProspect[]>([]); const [actions, setActions] = useState<ArtistProspectAction[]>([]); const [prospectId, setProspectId] = useState(''); const [action, setAction] = useState(''); const [owner, setOwner] = useState('Owner'); const [priority, setPriority] = useState<ArtistProspectActionPriority>('Normal'); const [dueDate, setDueDate] = useState(''); const [focus, setFocus] = useState('All prospects'); const [view, setView] = useState('Open'); const [filterPriority, setFilterPriority] = useState('All priorities'); const [ownerFilter, setOwnerFilter] = useState(''); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(ARTIST_PROSPECTS_KEY), AsyncStorage.getItem(ARTIST_PROSPECT_ACTIONS_KEY)]).then(([prospectValue, actionValue]) => { setProspects(readArtistProspects(prospectValue)); setActions(readArtistProspectActions(actionValue)); }).catch(() => setError('Private prospect follow-up data could not be read on this device.')).finally(() => setReady(true)); }, []);
  useEffect(() => { if (!ready) return; const requestedId = routeProspect || (Platform.OS === 'web' && typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('prospect') ?? undefined : undefined); if (!requestedId) return; const requested = prospects.find(item => item.id === requestedId); if (requested) { chooseProspect(requested); setFocus(requested.id); } }, [ready, routeProspect, prospects]);
  function chooseProspect(item: ArtistProspect) { setProspectId(item.id); setAction(artistProspectNextStep(item)); setMessage(null); setError(null); }
  async function persist(next: ArtistProspectAction[]) { await AsyncStorage.setItem(ARTIST_PROSPECT_ACTIONS_KEY, JSON.stringify(next)); setActions(next); }
  async function add() { const prospect = prospects.find(item => item.id === prospectId); if (!prospect || !action.trim() || !owner.trim()) { setError('Choose a private prospect and enter an action and responsible owner role.'); return; } setBusy(true); setError(null); const item: ArtistProspectAction = { id: `prospect-action-${Date.now()}`, prospectId, prospectName: prospect.name, action: action.trim(), owner: owner.trim(), priority, dueDate: dueDate.trim(), completed: false, updatedAt: new Date().toISOString() }; try { await persist([item, ...actions]); setAction(''); setDueDate(''); setMessage('Private prospect follow-up saved on this device. No person was assigned, contacted, or notified.'); } catch { setError('The follow-up could not be saved. Existing actions were kept.'); } finally { setBusy(false); } }
  async function toggle(item: ArtistProspectAction) { setBusy(true); setError(null); try { await persist(actions.map(value => value.id === item.id ? { ...value, completed: !value.completed, updatedAt: new Date().toISOString() } : value)); setMessage(item.completed ? 'Private prospect follow-up reopened.' : 'Private prospect follow-up marked complete. No official workflow changed.'); } catch { setError('The follow-up could not be updated.'); } finally { setBusy(false); } }
  async function remove(id: string) { setBusy(true); setError(null); try { await persist(actions.filter(item => item.id !== id)); setMessage('Private prospect follow-up removed from this device.'); } catch { setError('The follow-up could not be removed.'); } finally { setBusy(false); } }
  const open = actions.filter(item => !item.completed); const completed = actions.filter(item => item.completed); const overdue = open.filter(item => prospectActionTiming(item.dueDate).state === 'overdue'); const unlinkedCount = actions.filter(item => !prospects.some(prospect => prospect.id === item.prospectId)).length;
  const visible = actions.filter(item => (focus === 'All prospects' || item.prospectId === focus) && (view === 'All' || (view === 'Open' ? !item.completed : item.completed)) && (filterPriority === 'All priorities' || item.priority === filterPriority) && (!ownerFilter.trim() || item.owner.toLowerCase().includes(ownerFilter.trim().toLowerCase()))).sort((a, b) => Number(a.completed) - Number(b.completed) || priorityRank(a.priority) - priorityRank(b.priority) || a.dueDate.localeCompare(b.dueDate));
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · PRIVATE FOLLOW-UP" title="Turn owner review into clear next steps." description="Create device-local follow-up actions with an owner role, priority, timing, and completion state. These are planning notes—not staff assignments, outreach, bookings, promises, or enrollment." /><PreviewNotice /><Card title="Separate from PTown staff workflow" description="No person is assigned or notified. Completing an item changes only this device copy and does not represent contact, approval, booking, or verified completion." />
    <SectionHeader title="Create private prospect follow-up" /><Text style={styles.cardTitle}>Private prospect</Text><View accessibilityRole="radiogroup" accessibilityLabel="Follow-up prospect" style={styles.grid}>{prospects.map(item => <Choice key={item.id} label={item.name} selected={prospectId === item.id} onPress={() => chooseProspect(item)} />)}</View>{!prospects.length && <Card title="No private prospects available" description="Create a private Artist Development prospect profile before adding follow-up actions." />}<Field label="Follow-up action" value={action} onChangeText={value => setAction(value.slice(0, 240))} placeholder="Specific owner planning step" /><Field label="Responsible owner role" value={owner} onChangeText={value => setOwner(value.slice(0, 120))} placeholder="Role—not private contact information" /><Text style={styles.cardTitle}>Priority</Text><View accessibilityRole="radiogroup" accessibilityLabel="Follow-up priority" style={styles.grid}>{priorities.map(item => <Choice key={item} label={item} selected={priority === item} onPress={() => setPriority(item)} />)}</View><Field label="Due date or timing note" value={dueDate} onChangeText={value => setDueDate(value.slice(0, 120))} placeholder="YYYY-MM-DD or planning note" /><ActionButton label="Save private prospect follow-up" disabled={!ready || busy} onPress={() => { void add(); }} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    <SectionHeader title="Owner follow-up summary" /><View style={styles.grid}><Metric title="Open" value={open.length} /><Metric title="Overdue" value={overdue.length} /><Metric title="Completed" value={completed.length} /><Metric title="Unlinked history" value={unlinkedCount} /></View>{unlinkedCount > 0 && <Button label={`Review ${unlinkedCount} unlinked ${unlinkedCount === 1 ? 'follow-up' : 'follow-ups'}`} href="/artist-prospect-actions-unlinked" />}<SectionHeader title="Filter prospect follow-ups" /><Text style={styles.cardTitle}>Private prospect</Text><View style={styles.grid}><Choice label="All prospects" selected={focus === 'All prospects'} onPress={() => setFocus('All prospects')} />{prospects.map(item => <Choice key={item.id} label={item.name} selected={focus === item.id} onPress={() => setFocus(item.id)} />)}</View><Text style={styles.cardTitle}>Completion view</Text><View style={styles.grid}>{['Open', 'Completed', 'All'].map(item => <Choice key={item} label={item} selected={view === item} onPress={() => setView(item)} />)}</View><Text style={styles.cardTitle}>Priority filter</Text><View style={styles.grid}>{['All priorities', ...priorities].map(item => <Choice key={item} label={item} selected={filterPriority === item} onPress={() => setFilterPriority(item)} />)}</View><Field label="Responsible owner role contains" value={ownerFilter} onChangeText={value => setOwnerFilter(value.slice(0, 120))} placeholder="Filter by owner role" />{(focus !== 'All prospects' || view !== 'Open' || filterPriority !== 'All priorities' || ownerFilter) && <ActionButton label="Reset prospect follow-up filters" secondary onPress={() => { setFocus('All prospects'); setView('Open'); setFilterPriority('All priorities'); setOwnerFilter(''); }} />}
    <SectionHeader title="Private prospect follow-ups" /><Text accessibilityLiveRegion="polite" style={styles.smallBody}>{visible.length} of {actions.length} private follow-ups shown</Text>{visible.length ? visible.map(item => { const timing = prospectActionTiming(item.dueDate, item.completed); return <View key={item.id} style={styles.card}><Text style={{ color: timing.state === 'overdue' ? '#E8AAA2' : item.completed ? theme.colors.green : theme.colors.gold, fontSize: 12, fontWeight: '700' }}>{timing.state === 'overdue' ? 'OVERDUE' : item.completed ? 'COMPLETED ON THIS DEVICE' : `${item.priority.toUpperCase()} PRIORITY`}</Text><Text style={styles.cardTitle}>{item.action}</Text><Body>{item.prospectName}{'\n'}Responsible owner role: {item.owner}{'\n'}Timing: {timing.label}</Body><ActionButton label={item.completed ? 'Reopen private prospect follow-up' : 'Mark private prospect follow-up complete'} disabled={busy} secondary onPress={() => { void toggle(item); }} /><ActionButton label="Remove private prospect follow-up" disabled={busy} secondary onPress={() => { void remove(item.id); }} /></View>; }) : <Card title="No private prospect follow-ups match" description="Create a follow-up, choose another filter, or reset the queue." />}
    <Button label="Back up or transfer prospects and follow-ups" href="/artist-prospect-backup" /><Button label="Manage private prospect profiles" href="/artist-prospects" secondary /><Button label="Return to Artist Development" href="/artist-development" secondary /><Footer />
  </Screen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} aria-checked={selected} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
function Metric({ title, value }: { title: string; value: number }) { return <View style={[styles.card, { minWidth: 150, flexGrow: 1 }]}><Text style={{ color: theme.colors.gold, fontSize: 28, fontWeight: '700' }}>{value}</Text><Text style={styles.cardTitle}>{title}</Text></View>; }
function priorityRank(value: ArtistProspectActionPriority) { return value === 'High' ? 0 : value === 'Normal' ? 1 : 2; }
