import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { ARTIST_PROSPECTS_KEY, artistProspectReadiness, readArtistProspects, type ArtistProspect, type ArtistProspectStatus, type ArtistProspectTrack } from '../src/utils/artistProspects';
import { theme } from '../src/theme';

const tracks: ArtistProspectTrack[] = ['Performance', 'Production', 'Culinary']; const statuses: ArtistProspectStatus[] = ['New lead', 'Needs materials', 'Ready for owner review'];
const blank = { name: '', track: 'Performance' as ArtistProspectTrack, market: '', portfolio: '', availability: '', notes: '', status: 'New lead' as ArtistProspectStatus };
export default function ArtistProspects() {
  const [prospects, setProspects] = useState<ArtistProspect[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [trackFilter, setTrackFilter] = useState('All tracks'); const [readinessFilter, setReadinessFilter] = useState('All readiness'); const [statusFilter, setStatusFilter] = useState('All statuses'); const [query, setQuery] = useState(''); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(ARTIST_PROSPECTS_KEY).then(value => setProspects(readArtistProspects(value))).catch(() => setError('Private prospect profiles could not be read on this device.')).finally(() => setReady(true)); }, []);
  function update<K extends keyof typeof form>(key: K, value: (typeof form)[K]) { setForm(current => ({ ...current, [key]: value })); setMessage(null); setError(null); }
  function reset() { setForm(blank); setEditing(null); setMessage(null); setError(null); }
  async function save() { if (!form.name.trim()) { setError('Enter an artist, creative, group, or project name.'); return; } setBusy(true); setError(null); const item: ArtistProspect = { ...form, id: editing ?? `prospect-${Date.now()}`, name: form.name.trim(), market: form.market.trim(), portfolio: form.portfolio.trim(), availability: form.availability.trim(), notes: form.notes.trim(), updatedAt: new Date().toISOString() }; const next = editing ? prospects.map(value => value.id === editing ? item : value) : [item, ...prospects]; try { await AsyncStorage.setItem(ARTIST_PROSPECTS_KEY, JSON.stringify(next)); setProspects(next); setForm(blank); setEditing(null); setMessage(editing ? 'Private prospect profile updated on this device.' : 'Private prospect profile saved on this device. Nothing was submitted or sent.'); } catch { setError('The private prospect profile could not be saved. Existing profiles were kept.'); } finally { setBusy(false); } }
  async function remove(id: string) { setBusy(true); setError(null); const next = prospects.filter(item => item.id !== id); try { await AsyncStorage.setItem(ARTIST_PROSPECTS_KEY, JSON.stringify(next)); setProspects(next); if (editing === id) reset(); setMessage('Private prospect profile removed from this device.'); } catch { setError('The profile could not be removed. Existing profiles were kept.'); } finally { setBusy(false); } }
  const visible = prospects.filter(item => (trackFilter === 'All tracks' || item.track === trackFilter) && (statusFilter === 'All statuses' || item.status === statusFilter) && (readinessFilter === 'All readiness' || (readinessFilter === 'Ready' ? artistProspectReadiness(item).ready : !artistProspectReadiness(item).ready)) && (!query.trim() || `${item.name} ${item.market} ${item.notes}`.toLowerCase().includes(query.trim().toLowerCase())));
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · PRIVATE PROSPECTS" title="Prepare the opportunity before outreach." description="Create device-local prospect profiles for performers, production creatives, and culinary artists. This private planning tool does not submit an application, contact anyone, promise a booking, or enroll a participant." /><PreviewNotice /><Card title="Owner planning—not public intake" description="Use roles, markets, public portfolio references, and planning notes only. Do not enter private contact details, credentials, financial, medical, identity, or legally sensitive information." />
    <SectionHeader title={editing ? 'Edit private prospect profile' : 'New private prospect profile'} /><Field label="Artist, creative, group, or project name" value={form.name} onChangeText={value => update('name', value.slice(0, 120))} placeholder="Public or working name" editable={ready && !busy} /><Text style={styles.cardTitle}>Development track</Text><View accessibilityRole="radiogroup" accessibilityLabel="Prospect development track" style={styles.grid}>{tracks.map(item => <Choice key={item} label={item} selected={form.track === item} onPress={() => update('track', item)} />)}</View><Field label="Home market or region" value={form.market} onChangeText={value => update('market', value.slice(0, 120))} placeholder="City, state, or regional market" /><Field label="Portfolio or work reference" value={form.portfolio} onChangeText={value => update('portfolio', value.slice(0, 300))} placeholder="Public link, reel title, menu, credits, or available on request" /><Field label="Availability or timing" value={form.availability} onChangeText={value => update('availability', value.slice(0, 160))} placeholder="Known window, follow-up timing, or not confirmed" /><Text style={styles.cardTitle}>Private planning status</Text><View accessibilityRole="radiogroup" accessibilityLabel="Prospect planning status" style={styles.grid}>{statuses.map(item => <Choice key={item} label={item} selected={form.status === item} onPress={() => update('status', item)} />)}</View><Field label="Owner planning notes" value={form.notes} onChangeText={value => update('notes', value.slice(0, 1000))} placeholder="Fit, public discovery source, material needed, and next owner decision" multiline style={{ minHeight: 120, textAlignVertical: 'top' }} /><ActionButton label={editing ? 'Update private prospect profile' : 'Save private prospect profile'} disabled={!ready || busy} onPress={() => { void save(); }} />{editing && <ActionButton label="Cancel editing prospect" disabled={busy} secondary onPress={reset} />}<Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    <SectionHeader title="Filter private prospects" /><Text style={styles.cardTitle}>Track</Text><View style={styles.grid}>{['All tracks', ...tracks].map(item => <Choice key={item} label={item} selected={trackFilter === item} onPress={() => setTrackFilter(item)} />)}</View><Text style={styles.cardTitle}>Readiness</Text><View style={styles.grid}>{['All readiness', 'Ready', 'Needs details'].map(item => <Choice key={item} label={item} selected={readinessFilter === item} onPress={() => setReadinessFilter(item)} />)}</View><Text style={styles.cardTitle}>Planning status</Text><View style={styles.grid}>{['All statuses', ...statuses].map(item => <Choice key={item} label={item} selected={statusFilter === item} onPress={() => setStatusFilter(item)} />)}</View><Field label="Prospect search" value={query} onChangeText={value => setQuery(value.slice(0, 120))} placeholder="Name, market, or planning note" />{(trackFilter !== 'All tracks' || readinessFilter !== 'All readiness' || statusFilter !== 'All statuses' || query) && <ActionButton label="Reset prospect filters" secondary onPress={() => { setTrackFilter('All tracks'); setReadinessFilter('All readiness'); setStatusFilter('All statuses'); setQuery(''); }} />}
    <SectionHeader title="Private prospects on this device" /><Text accessibilityLiveRegion="polite" style={styles.smallBody}>{visible.length} of {prospects.length} private prospects shown</Text>{!ready ? <Body>Loading private prospect profiles…</Body> : visible.length ? visible.map(item => { const readiness = artistProspectReadiness(item); return <View key={item.id} style={styles.card}><Text style={{ color: readiness.ready ? theme.colors.green : theme.colors.gold, fontSize: 12, fontWeight: '700' }}>{readiness.ready ? 'READY FOR OWNER REVIEW' : 'NEEDS PLANNING DETAILS'} · {item.track.toUpperCase()}</Text><Text style={styles.cardTitle}>{item.name}</Text><Body>Status: {item.status}{'\n'}Market: {item.market || 'Not entered'}{'\n'}Portfolio/work: {item.portfolio || 'Not entered'}{'\n'}Availability: {item.availability || 'Not entered'}{readiness.missing.length ? `\nMissing: ${readiness.missing.join(', ')}` : ''}{item.notes ? `\nNotes: ${item.notes}` : ''}</Body><Button label={`Review ${item.name}`} href={{ pathname: '/artist-prospects/[id]', params: { id: item.id } }} /><ActionButton label={`Edit ${item.name}`} disabled={busy} secondary onPress={() => { setEditing(item.id); setForm({ name: item.name, track: item.track, market: item.market, portfolio: item.portfolio, availability: item.availability, notes: item.notes, status: item.status }); setMessage(null); }} /><ActionButton label={`Remove ${item.name}`} disabled={busy} secondary onPress={() => { void remove(item.id); }} /></View>; }) : prospects.length ? <Card title="No private prospects match" description="Choose another filter or reset the prospect list." /> : <Card title="No private prospect profiles" description="Create a device-local profile above. Nothing will be submitted or shared with PTown staff." />}
    <Button label="Return to Artist Development" href="/artist-development" secondary /><Footer />
  </Screen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
