import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { Platform, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { ARTIST_PROSPECT_ACTIONS_KEY, readArtistProspectActions, type ArtistProspectAction } from '../src/utils/artistProspectActions';
import { createArtistProspectBundle, inspectArtistProspectBundle, MAX_ARTIST_PROSPECT_BUNDLE, readArtistProspectBundle, type ArtistProspectBundle } from '../src/utils/artistProspectBundle';
import { ARTIST_PROSPECTS_KEY, readArtistProspects, type ArtistProspect } from '../src/utils/artistProspects';

export default function ArtistProspectBackup() {
  const [prospects, setProspects] = useState<ArtistProspect[]>([]); const [actions, setActions] = useState<ArtistProspectAction[]>([]); const [text, setText] = useState(''); const [incoming, setIncoming] = useState<ArtistProspectBundle | null>(null); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(ARTIST_PROSPECTS_KEY), AsyncStorage.getItem(ARTIST_PROSPECT_ACTIONS_KEY)]).then(([prospectValue, actionValue]) => { setProspects(readArtistProspects(prospectValue)); setActions(readArtistProspectActions(actionValue)); }).catch(() => setError('Private Artist Development data could not be read on this device.')).finally(() => setReady(true)); }, []);
  const code = ready && (prospects.length || actions.length) ? createArtistProspectBundle({ prospects, actions }) : ''; const linked = actions.filter(item => prospects.some(prospect => prospect.id === item.prospectId)).length; const incomingLinked = incoming?.actions.filter(item => incoming.prospects.some(prospect => prospect.id === item.prospectId)).length ?? 0; const incomingIssues = incoming ? inspectArtistProspectBundle(incoming) : [];
  async function copy() { setBusy(true); setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(code); } else if (!await Clipboard.setStringAsync(code)) throw new Error(); setMessage('Private Artist Development transfer code copied. Keep it secure.'); } catch { setError('Copy is unavailable. Select the complete transfer code and copy it manually.'); } finally { setBusy(false); } }
  function review() { setIncoming(null); setMessage(null); setError(null); try { setIncoming(readArtistProspectBundle(text)); } catch { setError('This Artist Development transfer code could not be read. Current device data is unchanged.'); } }
  async function replace() { if (!incoming) return; setBusy(true); setMessage(null); setError(null); try { await AsyncStorage.multiSet([[ARTIST_PROSPECTS_KEY, JSON.stringify(incoming.prospects)], [ARTIST_PROSPECT_ACTIONS_KEY, JSON.stringify(incoming.actions)]]); setProspects(incoming.prospects); setActions(incoming.actions); setIncoming(null); setText(''); setMessage('Private prospects and follow-ups were replaced together on this device.'); } catch { setError('Artist Development replacement failed. Existing private data was kept.'); } finally { setBusy(false); } }
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · PRIVATE TRANSFER" title="Move prospects and follow-ups together." description="Create one device-controlled transfer code for private prospect profiles and their linked owner follow-up history." /><PreviewNotice /><Card title="Private planning data—not outreach" description="This code may contain names, public work references, market, availability, owner notes, and follow-up history. It does not merge, sync, contact, book, promise, approve, assign, or enroll." />
    <SectionHeader title="Back up this device" />{!ready ? <Body>Loading private Artist Development data…</Body> : code ? <View style={styles.card}><Body>{prospects.length} private {prospects.length === 1 ? 'prospect' : 'prospects'} · {actions.length} private {actions.length === 1 ? 'follow-up' : 'follow-ups'}{`\n`}{linked} linked · {actions.length - linked} unlinked history</Body><ActionButton label="Copy private Artist Development transfer code" disabled={busy} onPress={() => { void copy(); }} /><Field label="Private Artist Development transfer code" value={code} multiline editable={false} style={{ minHeight: 220, textAlignVertical: 'top', fontSize: 12 }} /></View> : <Card title="No private Artist Development data to transfer" description="Create a prospect profile or follow-up first, or restore a reviewed transfer below." />}
    <SectionHeader title="Review a transfer" /><Field label="Paste private Artist Development transfer code" value={text} onChangeText={value => { setText(value); setIncoming(null); setMessage(null); setError(null); }} maxLength={MAX_ARTIST_PROSPECT_BUNDLE} multiline autoCapitalize="none" autoCorrect={false} style={{ minHeight: 180, textAlignVertical: 'top' }} /><ActionButton label="Review private Artist Development transfer" disabled={!text.trim() || busy} secondary onPress={review} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {incoming && <View style={styles.card}><SectionHeader title="Review before replacing" /><Body>{incoming.prospects.length} incoming private {incoming.prospects.length === 1 ? 'prospect' : 'prospects'} · {incoming.actions.length} incoming private {incoming.actions.length === 1 ? 'follow-up' : 'follow-ups'}{`\n`}{incomingLinked} linked · {incoming.actions.length - incomingLinked} unlinked history{`\n\n`}Confirming overwrites both current device lists. It does not merge.</Body><SectionHeader title="Transfer integrity report" />{incomingIssues.length ? <><Card title={`${incomingIssues.length} integrity ${incomingIssues.length === 1 ? 'finding' : 'findings'} need review`} description="The transfer is structurally valid, but these private relationships may need cleanup after replacement." />{incomingIssues.map(issue => <View key={issue.key} style={{ gap: 4 }}><Text style={styles.cardTitle}>{issue.title}</Text><Body>{issue.detail}</Body></View>)}</> : <Card title="No relationship issues found" description="Prospect names are distinct, every follow-up points to an included profile, and stored names match their linked prospects." />}{incoming.prospects.map(item => <View key={item.id}><Text style={styles.cardTitle}>{item.name}</Text><Body>{item.track} · {item.status} · {incoming.actions.filter(action => action.prospectId === item.id).length} linked follow-ups</Body></View>)}<ActionButton label="Replace private prospects and follow-ups together" disabled={busy} onPress={() => { void replace(); }} /><ActionButton label="Cancel Artist Development replacement" disabled={busy} secondary onPress={() => setIncoming(null)} /></View>}
    <Button label="Manage private prospect profiles" href="/artist-prospects" secondary /><Button label="Open private prospect follow-ups" href="/artist-prospect-actions" secondary /><Footer />
  </Screen>;
}
