import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ActionButton, Feedback, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { ARTIST_PROSPECT_ACTIONS_KEY, prospectActionTiming, readArtistProspectActions, type ArtistProspectAction } from '../src/utils/artistProspectActions';
import { ARTIST_PROSPECTS_KEY, readArtistProspects, type ArtistProspect } from '../src/utils/artistProspects';
import { theme } from '../src/theme';

export default function ArtistProspectActionsUnlinked() {
  const [prospects, setProspects] = useState<ArtistProspect[]>([]); const [actions, setActions] = useState<ArtistProspectAction[]>([]); const [targets, setTargets] = useState<Record<string, string>>({}); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(ARTIST_PROSPECTS_KEY), AsyncStorage.getItem(ARTIST_PROSPECT_ACTIONS_KEY)]).then(([prospectValue, actionValue]) => { setProspects(readArtistProspects(prospectValue)); setActions(readArtistProspectActions(actionValue)); }).catch(() => setError('Unlinked prospect follow-up history could not be reviewed on this device.')).finally(() => setReady(true)); }, []);
  const unlinked = actions.filter(item => !prospects.some(prospect => prospect.id === item.prospectId));
  async function persist(next: ArtistProspectAction[], success: string) { setBusy(true); setError(null); setMessage(null); try { await AsyncStorage.setItem(ARTIST_PROSPECT_ACTIONS_KEY, JSON.stringify(next)); setActions(next); setMessage(success); } catch { setError('The private follow-up history could not be changed. Existing actions were kept.'); } finally { setBusy(false); } }
  function reconnect(item: ArtistProspectAction) { const prospect = prospects.find(value => value.id === targets[item.id]); if (!prospect) { setError('Choose a private prospect before reconnecting this follow-up.'); return; } void persist(actions.map(value => value.id === item.id ? { ...value, prospectId: prospect.id, prospectName: prospect.name, updatedAt: new Date().toISOString() } : value), `${item.action} was reconnected to ${prospect.name}.`); }
  if (!ready) return <Screen><Body>Reviewing unlinked prospect follow-ups…</Body></Screen>;
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · PRIVATE HISTORY REVIEW" title="Reconnect, retain, or remove unlinked follow-ups." description="These device-local owner actions refer to prospect profiles that are no longer on this device. Reviewing them does not contact, book, assign, promise, or enroll anyone." /><PreviewNotice /><Card title={`${unlinked.length} unlinked private ${unlinked.length === 1 ? 'follow-up' : 'follow-ups'}`} description="Keeping an item preserves its previous prospect name. Reconnecting updates it to a current private profile. Removing deletes only this device copy." /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {unlinked.length ? unlinked.map(item => { const timing = prospectActionTiming(item.dueDate, item.completed); return <View key={item.id} style={styles.card}><Text style={{ color: theme.colors.gold, fontSize: 12, fontWeight: '700' }}>UNLINKED · {item.completed ? 'COMPLETED' : item.priority.toUpperCase()}</Text><Text style={styles.cardTitle}>{item.action}</Text><Body>Previous prospect: {item.prospectName}{'\n'}Responsible owner role: {item.owner}{'\n'}Timing: {timing.label}</Body><SectionHeader title="Reconnect to a current private prospect" /><View accessibilityRole="radiogroup" accessibilityLabel={`Destination for ${item.action}`} style={styles.grid}>{prospects.map(prospect => <Choice key={prospect.id} label={prospect.name} selected={targets[item.id] === prospect.id} onPress={() => setTargets(current => ({ ...current, [item.id]: prospect.id }))} />)}</View>{!prospects.length && <Body>Create another private prospect profile before reconnecting this item.</Body>}<ActionButton label={`Reconnect ${item.action}`} disabled={busy || !prospects.length} onPress={() => reconnect(item)} /><ActionButton label={`Keep ${item.action} as unlinked history`} disabled={busy} secondary onPress={() => { setError(null); setMessage(`${item.action} remains preserved as unlinked private history.`); }} /><ActionButton label={`Remove ${item.action} from private history`} disabled={busy} secondary onPress={() => { void persist(actions.filter(value => value.id !== item.id), `${item.action} was removed from private history.`); }} /></View>; }) : <Card title="No unlinked private follow-ups" description="Every saved follow-up is connected to a current private prospect, or no follow-ups are stored on this device." />}
    <Button label="Return to private prospect follow-ups" href="/artist-prospect-actions" secondary /><Footer />
  </Screen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
