import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform, Text, View } from 'react-native';
import { useEffect, useRef, useState } from 'react';
import * as Clipboard from 'expo-clipboard';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { createMediaDraftTransfer, MAX_MEDIA_DRAFT_TRANSFER, MEDIA_DRAFTS_KEY, readMediaDrafts, readMediaDraftTransfer, type MediaDraft } from '../src/utils/mediaDrafts';

export default function MediaDraftBackup() {
  const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [ready, setReady] = useState(false); const [text, setText] = useState(''); const [incoming, setIncoming] = useState<MediaDraft[] | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(MEDIA_DRAFTS_KEY).then(value => setDrafts(readMediaDrafts(value))).catch(() => setError('Private production drafts could not be read on this device.')).finally(() => setReady(true)); }, []);
  const code = ready && drafts.length ? createMediaDraftTransfer(drafts) : ''; const currentCode = useRef(code); currentCode.current = code;
  async function copy() { const outgoing = code; setBusy(true); setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(outgoing); } else if (!await Clipboard.setStringAsync(outgoing)) throw new Error(); if (currentCode.current === outgoing) setMessage('Private production-draft transfer code copied. Keep it secure.'); } catch { setError('Copy is unavailable. Select the complete transfer code and copy it manually.'); } finally { setBusy(false); } }
  function review() { setMessage(null); setError(null); setIncoming(null); try { setIncoming(readMediaDraftTransfer(text)); } catch { setError('This production-draft transfer code could not be read. Current drafts are unchanged.'); } }
  async function replace() { if (!incoming) return; setBusy(true); setMessage(null); setError(null); try { await AsyncStorage.setItem(MEDIA_DRAFTS_KEY, JSON.stringify(incoming)); setDrafts(incoming); setIncoming(null); setText(''); setMessage('Private production drafts replaced on this device. Nothing was submitted or shared with PTown.'); } catch { setError('Draft replacement failed. Existing drafts were kept.'); } finally { setBusy(false); } }
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · PRIVATE DRAFT TRANSFER" title="Move production drafts deliberately." description="Copy a private transfer code, review it on another authorized device, and explicitly replace that device’s private production drafts." /><PreviewNotice />
    <Card title="Treat the transfer code as private" description="The code contains production titles, responsible roles, timing, status, and notes. It does not use a PTown account or cloud sync. Do not include confidential, credential, medical, financial, or legally sensitive information." />
    <SectionHeader title="Back up this device" />{!ready ? <Body>Loading private drafts…</Body> : !drafts.length ? <Card title="No private production drafts to transfer" description="Create a private production draft first, or restore a reviewed transfer below." /> : <View style={styles.card}><Body>{drafts.length} private {drafts.length === 1 ? 'draft' : 'drafts'} will be included.</Body><ActionButton label="Copy private draft transfer code" disabled={busy} onPress={() => { void copy(); }} /><Field label="Private draft transfer code" value={code} multiline editable={false} style={{ minHeight: 220, textAlignVertical: 'top', fontSize: 12, lineHeight: 19 }} /></View>}
    <SectionHeader title="Review a transfer" /><Field label="Paste private draft transfer code" value={text} onChangeText={value => { setText(value); setIncoming(null); setMessage(null); setError(null); }} maxLength={MAX_MEDIA_DRAFT_TRANSFER} multiline autoCapitalize="none" autoCorrect={false} style={{ minHeight: 180, textAlignVertical: 'top' }} /><ActionButton label="Review private draft transfer" disabled={!text.trim() || busy} secondary onPress={review} />
    <Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {incoming && <View style={styles.card}><SectionHeader title="Review before replacing" /><Body>{incoming.length} incoming private {incoming.length === 1 ? 'draft' : 'drafts'}. Replacing does not merge. Current device drafts will be overwritten only after you confirm.</Body>{incoming.map(draft => <View key={draft.id} style={{ gap: 4 }}><Text style={styles.cardTitle}>{draft.title}</Text><Body>{draft.status} · {draft.division} · {draft.owner}</Body></View>)}<ActionButton label="Replace this device’s private drafts" disabled={busy} onPress={() => { void replace(); }} /><ActionButton label="Cancel draft replacement" disabled={busy} secondary onPress={() => setIncoming(null)} /></View>}
    <Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer />
  </Screen>;
}
