import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { MEDIA_ACTIONS_KEY, mediaActionTiming, readMediaActions, type MediaAction, type MediaActionPriority } from '../src/utils/mediaActions';
import { MEDIA_DRAFTS_KEY, mediaDraftReadiness, readMediaDrafts, type MediaDraft } from '../src/utils/mediaDrafts';
import { theme } from '../src/theme';

const priorities: MediaActionPriority[] = ['High', 'Normal', 'Low'];
export default function MediaActions() {
  const router = useRouter(); const params = useLocalSearchParams<{ draft?: string | string[]; focus?: string | string[]; view?: string | string[]; priority?: string | string[]; owner?: string | string[] }>(); const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [actions, setActions] = useState<MediaAction[]>([]); const [draftId, setDraftId] = useState(''); const [action, setAction] = useState(''); const [owner, setOwner] = useState(''); const [priority, setPriority] = useState<MediaActionPriority>('Normal'); const [dueDate, setDueDate] = useState(''); const [view, setView] = useState('Open'); const [filterPriority, setFilterPriority] = useState('All priorities'); const [ownerFilter, setOwnerFilter] = useState(''); const [focus, setFocus] = useState('All drafts'); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(MEDIA_DRAFTS_KEY), AsyncStorage.getItem(MEDIA_ACTIONS_KEY)]).then(([draftValue, actionValue]) => { const loaded = readMediaDrafts(draftValue); setDrafts(loaded); setActions(readMediaActions(actionValue)); const requested = typeof params.draft === 'string' ? loaded.find(item => item.id === params.draft) : undefined; if (requested) chooseDraft(requested); }).catch(() => setError('Private action queue data could not be read on this device.')).finally(() => setReady(true)); }, [params.draft]);
  useEffect(() => setView(params.view === 'Completed' || params.view === 'All' ? params.view : 'Open'), [params.view]); useEffect(() => setFilterPriority(['High', 'Normal', 'Low'].includes(String(params.priority)) ? String(params.priority) : 'All priorities'), [params.priority]); useEffect(() => setOwnerFilter(typeof params.owner === 'string' ? params.owner.slice(0, 120) : ''), [params.owner]);
  useEffect(() => setFocus(typeof params.focus === 'string' && drafts.some(item => item.id === params.focus) ? params.focus : 'All drafts'), [params.focus, drafts.length]);
  function chooseDraft(draft: MediaDraft) { const readiness = mediaDraftReadiness(draft); setDraftId(draft.id); setOwner(draft.owner); setAction(readiness.recommendation ? `Complete ${readiness.recommendation.title} planning review` : 'Complete authorized supporting-record verification'); setMessage(null); setError(null); }
  async function persist(next: MediaAction[]) { await AsyncStorage.setItem(MEDIA_ACTIONS_KEY, JSON.stringify(next)); setActions(next); }
  async function add() { const draft = drafts.find(item => item.id === draftId); if (!draft || !action.trim() || !owner.trim()) { setError('Choose a private draft and enter an action and responsible role.'); return; } setBusy(true); setError(null); setMessage(null); const item: MediaAction = { id: `action-${Date.now()}`, draftId, draftTitle: draft.title, action: action.trim(), owner: owner.trim(), priority, dueDate: dueDate.trim(), completed: false, updatedAt: new Date().toISOString() }; try { await persist([item, ...actions]); setAction(''); setDueDate(''); setMessage('Private follow-up action saved on this device. No staff member was assigned or notified.'); router.setParams({ draft: undefined }); } catch { setError('The action could not be saved. Existing actions were kept.'); } finally { setBusy(false); } }
  async function toggle(item: MediaAction) { setBusy(true); setError(null); try { await persist(actions.map(actionItem => actionItem.id === item.id ? { ...actionItem, completed: !actionItem.completed, updatedAt: new Date().toISOString() } : actionItem)); setMessage(item.completed ? 'Private action reopened.' : 'Private action marked complete. No official workflow status changed.'); } catch { setError('The action could not be updated.'); } finally { setBusy(false); } }
  async function remove(id: string) { setBusy(true); setError(null); try { await persist(actions.filter(item => item.id !== id)); setMessage('Private follow-up action removed from this device.'); } catch { setError('The action could not be removed.'); } finally { setBusy(false); } }
  const openCount = actions.filter(item => !item.completed).length; const completedCount = actions.length - openCount; const overdueCount = actions.filter(item => mediaActionTiming(item.dueDate, item.completed).state === 'overdue').length;
  const visible = actions.filter(item => (focus === 'All drafts' || item.draftId === focus) && (view === 'All' || (view === 'Open' ? !item.completed : item.completed)) && (filterPriority === 'All priorities' || item.priority === filterPriority) && (!ownerFilter.trim() || item.owner.toLowerCase().includes(ownerFilter.trim().toLowerCase()))).sort((a, b) => Number(a.completed) - Number(b.completed) || priorityRank(a.priority) - priorityRank(b.priority) || a.dueDate.localeCompare(b.dueDate));
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · PRIVATE OWNER ACTION QUEUE" title="Turn readiness findings into clear follow-up." description="Create device-local follow-up actions with priority, responsible role, due date, and completion state. No person is assigned or notified." /><PreviewNotice /><Card title="Planning queue—not staff workflow" description="Actions stay on this device and are not official assignments, approvals, calendar events, messages, or proof of completion." />
    <SectionHeader title="Create follow-up action" /><Text style={styles.cardTitle}>Private production draft</Text><View accessibilityRole="radiogroup" accessibilityLabel="Action draft" style={styles.grid}>{drafts.map(draft => <Choice key={draft.id} label={draft.title} selected={draftId === draft.id} onPress={() => chooseDraft(draft)} />)}</View>
    <Field label="Follow-up action" value={action} onChangeText={value => { setAction(value.slice(0, 240)); setMessage(null); }} placeholder="Specific next step" /><Field label="Responsible role" value={owner} onChangeText={value => setOwner(value.slice(0, 120))} placeholder="Role—not private contact information" />
    <Text style={styles.cardTitle}>Priority</Text><View accessibilityRole="radiogroup" accessibilityLabel="Action priority" style={styles.grid}>{priorities.map(item => <Choice key={item} label={item} selected={priority === item} onPress={() => setPriority(item)} />)}</View><Field label="Due date or timing note" value={dueDate} onChangeText={value => setDueDate(value.slice(0, 120))} placeholder="YYYY-MM-DD or planning note" /><ActionButton label="Save private follow-up action" disabled={!ready || busy} onPress={() => { void add(); }} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    <SectionHeader title="Owner action summary" /><View style={styles.grid}><Metric title="Open" value={openCount} /><Metric title="Overdue" value={overdueCount} /><Metric title="Completed" value={completedCount} /></View>
    <SectionHeader title="Filter action queue" /><Text style={styles.cardTitle}>Private draft</Text><View style={styles.grid}><Choice label="All drafts" selected={focus === 'All drafts'} onPress={() => { setFocus('All drafts'); router.setParams({ focus: undefined }); }} />{drafts.map(item => <Choice key={item.id} label={item.title} selected={focus === item.id} onPress={() => { setFocus(item.id); router.setParams({ focus: item.id }); }} />)}</View><Text style={styles.cardTitle}>View</Text><View style={styles.grid}>{['Open', 'Completed', 'All'].map(item => <Choice key={item} label={item} selected={view === item} onPress={() => { setView(item); router.setParams({ view: item === 'Open' ? undefined : item }); }} />)}</View><Text style={styles.cardTitle}>Priority filter</Text><View style={styles.grid}>{['All priorities', ...priorities].map(item => <Choice key={item} label={item} selected={filterPriority === item} onPress={() => { setFilterPriority(item); router.setParams({ priority: item === 'All priorities' ? undefined : item }); }} />)}</View><Field label="Action owner contains" value={ownerFilter} onChangeText={value => { const next = value.slice(0, 120); setOwnerFilter(next); router.setParams({ owner: next || undefined }); }} placeholder="Filter by responsible role" />
    {(focus !== 'All drafts' || view !== 'Open' || filterPriority !== 'All priorities' || ownerFilter) && <ActionButton label="Reset action filters" secondary onPress={() => { setFocus('All drafts'); setView('Open'); setFilterPriority('All priorities'); setOwnerFilter(''); router.setParams({ focus: undefined, view: undefined, priority: undefined, owner: undefined }); }} />}
    <SectionHeader title="Follow-up actions" /><Text accessibilityLiveRegion="polite" style={styles.smallBody}>{visible.length} of {actions.length} private actions shown</Text>{visible.length ? visible.map(item => <ActionCard key={item.id} item={item} busy={busy} onToggle={() => { void toggle(item); }} onRemove={() => { void remove(item.id); }} />) : <Card title="No private actions match" description="Create an action, choose another filter, or reset the queue." />}
    <Button label="Back up or transfer private actions" href="/media-action-backup" /><Button label="Open owner readiness report" href="/media-readiness" secondary /><Footer />
  </Screen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
function ActionCard({ item, busy, onToggle, onRemove }: { item: MediaAction; busy: boolean; onToggle: () => void; onRemove: () => void }) { const timing = mediaActionTiming(item.dueDate, item.completed); return <View style={styles.card}><Text style={{ color: timing.state === 'overdue' ? '#E8AAA2' : item.completed ? theme.colors.green : theme.colors.gold, fontSize: 12, fontWeight: '700' }}>{timing.state === 'overdue' ? 'OVERDUE' : item.completed ? 'COMPLETED ON THIS DEVICE' : `${item.priority.toUpperCase()} PRIORITY`}</Text><Text style={styles.cardTitle}>{item.action}</Text><Body>{item.draftTitle}{'\n'}Responsible role: {item.owner}{'\n'}Timing: {timing.label}</Body><ActionButton label={item.completed ? 'Reopen private action' : 'Mark private action complete'} disabled={busy} secondary onPress={onToggle} /><ActionButton label="Remove private action" disabled={busy} secondary onPress={onRemove} /></View>; }
function priorityRank(value: MediaActionPriority) { return value === 'High' ? 0 : value === 'Normal' ? 1 : 2; }
function Metric({ title, value }: { title: string; value: number }) { return <View style={[styles.card, { minWidth: 150, flexGrow: 1 }]}><Text style={{ color: theme.colors.gold, fontSize: 28, fontWeight: '700' }}>{value}</Text><Text style={styles.cardTitle}>{title}</Text></View>; }
