import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import * as Clipboard from 'expo-clipboard';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { MEDIA_DRAFTS_KEY, mediaDraftReadiness, readMediaDrafts, type MediaDraft } from '../src/utils/mediaDrafts';
import { theme } from '../src/theme';

export default function MediaReadiness() {
  const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [ready, setReady] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(MEDIA_DRAFTS_KEY).then(value => setDrafts(readMediaDrafts(value))).catch(() => setError('Private production drafts could not be read for this report.')).finally(() => setReady(true)); }, []);
  const rows = drafts.map(draft => ({ draft, readiness: mediaDraftReadiness(draft) })); const blocked = rows.filter(row => row.readiness.blocked).length; const stale = rows.filter(row => row.readiness.gates.some(gate => gate.recordQuality.state === 'stale')).length; const timing = rows.filter(row => row.readiness.timing.state === 'missing' || row.readiness.timing.state === 'overdue').length;
  const summary = ['PTOWN MEDIA GROUP — PRIVATE READINESS REPORT', '', `Private drafts: ${drafts.length}`, `Blocked by planning gates or record quality: ${blocked}`, `Drafts with stale record references: ${stale}`, `Missing or passed timing: ${timing}`, '', ...rows.flatMap(({ draft, readiness }) => [`${draft.title} — ${draft.status}`, `Owner: ${draft.owner}`, `Timing: ${readiness.timing.label}`, `Readiness: ${readiness.blocked ? 'Needs attention' : 'Planning gates marked and references current'}`, `Next: ${readiness.recommendation ? readiness.recommendation.title : 'Authorized verification'}`, '']), 'PRIVATE DEVICE REPORT — Not an official approval, assignment, or production authorization.'].join('\n');
  async function copy() { setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(summary); } else if (!await Clipboard.setStringAsync(summary)) throw new Error(); setMessage('Private readiness report copied. It is not an official approval or authorization.'); } catch { setError('Copy is unavailable. Select the report and copy it manually.'); } }
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · OWNER READINESS VIEW" title="See what needs attention before anything advances." description="Review private production drafts across planning gates, record quality, timing, status, ownership, and recommended next action." /><PreviewNotice />
    <Card title="Private planning report" description="This device-only report reads private drafts stored here. It does not verify records, notify staff, assign work, change status, approve content, or authorize production." />
    {!ready ? <Body>Preparing private readiness report…</Body> : !drafts.length ? <Card title="No private drafts to report" description="Create a private production draft first. Sample dashboard projects are not included in this owner view." /> : <><View style={styles.grid}><Metric title="Private drafts" value={drafts.length} /><Metric title="Need attention" value={blocked} /><Metric title="Stale references" value={stale} /><Metric title="Timing attention" value={timing} /></View>
      <SectionHeader title="Draft readiness" />{rows.map(({ draft, readiness }) => <View key={draft.id} style={styles.card}><Text style={{ color: readiness.blocked ? '#E8AAA2' : theme.colors.green, fontSize: 12, fontWeight: '700' }}>{readiness.blocked ? 'NEEDS ATTENTION' : 'PLANNING GATES MARKED'}</Text><Text style={styles.cardTitle}>{draft.title}</Text><Body>{draft.status} · {draft.division}{'\n'}Owner: {draft.owner}{'\n'}Timing: {readiness.timing.label}{'\n'}Record-quality issues: {readiness.recordIssues}{'\n'}Recommended next action: {readiness.recommendation?.title ?? 'Authorized verification of supporting records'}</Body><Button label={`Review ${draft.title}`} href={{ pathname: '/media-drafts/[id]', params: { id: draft.id } }} secondary /></View>)}
      <SectionHeader title="Copy owner report" /><Field label="Private readiness report" value={summary} multiline editable={false} style={{ minHeight: 340, textAlignVertical: 'top', lineHeight: 22 }} /><ActionButton label="Copy private readiness report" onPress={() => { void copy(); }} /></>}
    <Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}<Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer />
  </Screen>;
}
function Metric({ title, value }: { title: string; value: number }) { return <View style={[styles.card, { minWidth: 180, flexGrow: 1 }]}><Text style={{ color: theme.colors.gold, fontSize: 30, fontWeight: '700' }}>{value}</Text><Text style={styles.cardTitle}>{title}</Text></View>; }
