import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { Platform, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { MEDIA_ACTIONS_KEY, readMediaActions, type MediaAction } from '../src/utils/mediaActions';
import { createMediaBundleTransfer, MAX_MEDIA_BUNDLE_TRANSFER, readMediaBundleTransfer, type MediaBundle } from '../src/utils/mediaBundle';
import { MEDIA_DRAFTS_KEY, readMediaDrafts, type MediaDraft } from '../src/utils/mediaDrafts';

export default function MediaBundleBackup() {
  const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [actions, setActions] = useState<MediaAction[]>([]); const [ready, setReady] = useState(false); const [text, setText] = useState(''); const [incoming, setIncoming] = useState<MediaBundle | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(MEDIA_DRAFTS_KEY), AsyncStorage.getItem(MEDIA_ACTIONS_KEY)]).then(([draftValue, actionValue]) => { setDrafts(readMediaDrafts(draftValue)); setActions(readMediaActions(actionValue)); }).catch(() => setError('Private Media Group data could not be read on this device.')).finally(() => setReady(true)); }, []);
  const code = ready && (drafts.length || actions.length) ? createMediaBundleTransfer({ drafts, actions }) : ''; const linkedCount = actions.filter(item => drafts.some(draft => draft.id === item.draftId)).length;
  async function copy() { setBusy(true); setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(code); } else if (!await Clipboard.setStringAsync(code)) throw new Error(); setMessage('Unified private Media Group transfer code copied. Keep it secure.'); } catch { setError('Copy is unavailable. Select the complete transfer code and copy it manually.'); } finally { setBusy(false); } }
  function review() { setIncoming(null); setMessage(null); setError(null); try { setIncoming(readMediaBundleTransfer(text)); } catch { setError('This unified Media Group transfer code could not be read. Current device data is unchanged.'); } }
  async function replace() { if (!incoming) return; setBusy(true); setMessage(null); setError(null); try { await AsyncStorage.multiSet([[MEDIA_DRAFTS_KEY, JSON.stringify(incoming.drafts)], [MEDIA_ACTIONS_KEY, JSON.stringify(incoming.actions)]]); setDrafts(incoming.drafts); setActions(incoming.actions); setIncoming(null); setText(''); setMessage('Private drafts and actions were replaced together on this device.'); } catch { setError('Unified replacement failed. Existing private Media Group data was kept.'); } finally { setBusy(false); } }
  const incomingLinked = incoming?.actions.filter(item => incoming.drafts.some(draft => draft.id === item.draftId)).length ?? 0;
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · UNIFIED PRIVATE TRANSFER" title="Move drafts and actions together." description="Create one reviewed transfer code for private production drafts, their workbooks and record references, and the owner action queue." /><PreviewNotice /><Card title="One device-controlled bundle" description="This replaces both private datasets together so linked actions keep their draft relationships. It does not merge, sync, submit, assign, notify, or create an account." />
    <SectionHeader title="Back up this device" />{!ready ? <Body>Loading private Media Group data…</Body> : code ? <View style={styles.card}><Body>{drafts.length} private {drafts.length === 1 ? 'draft' : 'drafts'} · {actions.length} private {actions.length === 1 ? 'action' : 'actions'}{`\n`}{linkedCount} linked · {actions.length - linkedCount} unlinked history</Body><ActionButton label="Copy unified Media Group transfer code" disabled={busy} onPress={() => { void copy(); }} /><Field label="Unified Media Group transfer code" value={code} multiline editable={false} style={{ minHeight: 220, textAlignVertical: 'top', fontSize: 12 }} /></View> : <Card title="No private Media Group data to transfer" description="Create a production draft or owner action first, or restore a reviewed unified transfer below." />}
    <SectionHeader title="Review a unified transfer" /><Field label="Paste unified Media Group transfer code" value={text} onChangeText={value => { setText(value); setIncoming(null); setMessage(null); setError(null); }} maxLength={MAX_MEDIA_BUNDLE_TRANSFER} multiline autoCapitalize="none" autoCorrect={false} style={{ minHeight: 180, textAlignVertical: 'top' }} /><ActionButton label="Review unified Media Group transfer" disabled={!text.trim() || busy} secondary onPress={review} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {incoming && <View style={styles.card}><SectionHeader title="Review before replacing both datasets" /><Body>{incoming.drafts.length} incoming private {incoming.drafts.length === 1 ? 'draft' : 'drafts'} · {incoming.actions.length} incoming private {incoming.actions.length === 1 ? 'action' : 'actions'}{`\n`}{incomingLinked} linked · {incoming.actions.length - incomingLinked} unlinked history{`\n\n`}Confirming overwrites both current device lists. It does not merge.</Body>{incoming.drafts.map(draft => <View key={draft.id}><Text style={styles.cardTitle}>{draft.title}</Text><Body>{draft.status} · {draft.division} · {incoming.actions.filter(item => item.draftId === draft.id).length} linked actions</Body></View>)}<ActionButton label="Replace private drafts and actions together" disabled={busy} onPress={() => { void replace(); }} /><ActionButton label="Cancel unified replacement" disabled={busy} secondary onPress={() => setIncoming(null)} /></View>}
    <Button label="Manage private production drafts" href="/media-drafts" secondary /><Button label="Open owner action queue" href="/media-actions" secondary /><Footer />
  </Screen>;
}
