import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import * as Clipboard from 'expo-clipboard';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { createMediaActionTransfer, MAX_MEDIA_ACTION_TRANSFER, MEDIA_ACTIONS_KEY, readMediaActions, readMediaActionTransfer, type MediaAction } from '../src/utils/mediaActions';

export default function MediaActionBackup() {
  const [actions, setActions] = useState<MediaAction[]>([]); const [ready, setReady] = useState(false); const [text, setText] = useState(''); const [incoming, setIncoming] = useState<MediaAction[] | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(MEDIA_ACTIONS_KEY).then(value => setActions(readMediaActions(value))).catch(() => setError('Private action queue could not be read on this device.')).finally(() => setReady(true)); }, []);
  const code = ready && actions.length ? createMediaActionTransfer(actions) : '';
  async function copy() { setBusy(true); setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(code); } else if (!await Clipboard.setStringAsync(code)) throw new Error(); setMessage('Private action-queue transfer code copied. Keep it secure.'); } catch { setError('Copy is unavailable. Select the complete code and copy it manually.'); } finally { setBusy(false); } }
  function review() { setIncoming(null); setMessage(null); setError(null); try { setIncoming(readMediaActionTransfer(text)); } catch { setError('This action-queue transfer code could not be read. Current actions are unchanged.'); } }
  async function replace() { if (!incoming) return; setBusy(true); setError(null); try { await AsyncStorage.setItem(MEDIA_ACTIONS_KEY, JSON.stringify(incoming)); setActions(incoming); setIncoming(null); setText(''); setMessage('Private action queue replaced on this device. No staff member was assigned or notified.'); } catch { setError('Action-queue replacement failed. Existing actions were kept.'); } finally { setBusy(false); } }
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · PRIVATE ACTION TRANSFER" title="Move the owner action queue deliberately." description="Copy, review, and explicitly replace private device follow-up actions without creating accounts, assignments, notifications, or cloud sync." /><PreviewNotice /><Card title="Private planning data" description="The code includes draft titles, action text, responsible roles, priorities, timing, and device completion state. Keep it secure." />
    <SectionHeader title="Back up this device" />{!ready ? <Body>Loading private actions…</Body> : actions.length ? <View style={styles.card}><Body>{actions.length} private {actions.length === 1 ? 'action' : 'actions'} included.</Body><ActionButton label="Copy private action transfer code" disabled={busy} onPress={() => { void copy(); }} /><Field label="Private action transfer code" value={code} multiline editable={false} style={{ minHeight: 220, textAlignVertical: 'top', fontSize: 12 }} /></View> : <Card title="No private actions to transfer" description="Create an owner follow-up action first, or restore a reviewed transfer below." />}
    <SectionHeader title="Review a transfer" /><Field label="Paste private action transfer code" value={text} onChangeText={value => { setText(value); setIncoming(null); setMessage(null); setError(null); }} maxLength={MAX_MEDIA_ACTION_TRANSFER} multiline style={{ minHeight: 180, textAlignVertical: 'top' }} /><ActionButton label="Review private action transfer" disabled={!text.trim() || busy} secondary onPress={review} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {incoming && <View style={styles.card}><SectionHeader title="Review before replacing" /><Body>{incoming.length} incoming private {incoming.length === 1 ? 'action' : 'actions'}. Replacement does not merge.</Body>{incoming.map(item => <View key={item.id}><Text style={styles.cardTitle}>{item.action}</Text><Body>{item.priority} · {item.owner} · {item.completed ? 'Completed' : 'Open'}</Body></View>)}<ActionButton label="Replace this device’s private actions" disabled={busy} onPress={() => { void replace(); }} /><ActionButton label="Cancel action replacement" disabled={busy} secondary onPress={() => setIncoming(null)} /></View>}
    <Button label="Move drafts and actions together" href="/media-bundle-backup" /><Button label="Return to owner action queue" href="/media-actions" secondary /><Footer />
  </Screen>;
}
