import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { ActionButton, Feedback, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { MEDIA_ACTIONS_KEY, mediaActionTiming, readMediaActions, type MediaAction } from '../src/utils/mediaActions';
import { MEDIA_DRAFTS_KEY, readMediaDrafts, type MediaDraft } from '../src/utils/mediaDrafts';
import { theme } from '../src/theme';

export default function MediaActionsUnlinked() {
  const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [actions, setActions] = useState<MediaAction[]>([]); const [targets, setTargets] = useState<Record<string, string>>({}); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(MEDIA_DRAFTS_KEY), AsyncStorage.getItem(MEDIA_ACTIONS_KEY)]).then(([draftValue, actionValue]) => { setDrafts(readMediaDrafts(draftValue)); setActions(readMediaActions(actionValue)); }).catch(() => setError('Unlinked action history could not be reviewed on this device.')).finally(() => setReady(true)); }, []);
  const unlinked = actions.filter(item => !drafts.some(draft => draft.id === item.draftId));
  async function persist(next: MediaAction[], success: string) { setBusy(true); setError(null); setMessage(null); try { await AsyncStorage.setItem(MEDIA_ACTIONS_KEY, JSON.stringify(next)); setActions(next); setMessage(success); } catch { setError('The action history could not be changed. Existing actions were kept.'); } finally { setBusy(false); } }
  function retain(item: MediaAction) { setError(null); setMessage(`${item.action} remains preserved as unlinked private history.`); }
  function reconnect(item: MediaAction) { const draft = drafts.find(value => value.id === targets[item.id]); if (!draft) { setError('Choose a private production draft before reconnecting this action.'); return; } void persist(actions.map(value => value.id === item.id ? { ...value, draftId: draft.id, draftTitle: draft.title, updatedAt: new Date().toISOString() } : value), `${item.action} was reconnected to ${draft.title}.`); }
  function remove(item: MediaAction) { void persist(actions.filter(value => value.id !== item.id), `${item.action} was removed from private history.`); }
  if (!ready) return <Screen><Body>Reviewing unlinked action history…</Body></Screen>;
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · PRIVATE HISTORY REVIEW" title="Reconnect, retain, or remove unlinked actions." description="These device-local actions refer to production drafts that are no longer on this device. Review each item without changing official records or notifying staff." /><PreviewNotice />
    <Card title={`${unlinked.length} unlinked private ${unlinked.length === 1 ? 'action' : 'actions'}`} description="Keeping an item preserves its historical draft title. Reconnecting updates it to a current private draft. Removing deletes only this device copy." />
    <Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {unlinked.length ? unlinked.map(item => { const timing = mediaActionTiming(item.dueDate, item.completed); return <View key={item.id} style={styles.card}><Text style={{ color: theme.colors.gold, fontSize: 12, fontWeight: '700' }}>UNLINKED · {item.completed ? 'COMPLETED' : item.priority.toUpperCase()}</Text><Text style={styles.cardTitle}>{item.action}</Text><Body>Previous draft: {item.draftTitle}{'\n'}Responsible role: {item.owner}{'\n'}Timing: {timing.label}</Body><SectionHeader title="Reconnect to a current private draft" /><View accessibilityRole="radiogroup" accessibilityLabel={`Destination for ${item.action}`} style={styles.grid}>{drafts.map(draft => <Choice key={draft.id} label={draft.title} selected={targets[item.id] === draft.id} onPress={() => setTargets(current => ({ ...current, [item.id]: draft.id }))} />)}</View>{!drafts.length && <Body>Create a private production draft before reconnecting this item.</Body>}<ActionButton label={`Reconnect ${item.action}`} disabled={busy || !drafts.length} onPress={() => reconnect(item)} /><ActionButton label={`Keep ${item.action} as unlinked history`} disabled={busy} secondary onPress={() => retain(item)} /><ActionButton label={`Remove ${item.action} from private history`} disabled={busy} secondary onPress={() => remove(item)} /></View>; }) : <Card title="No unlinked private actions" description="Every saved action is connected to a current private production draft, or no actions are stored on this device." />}
    <Button label="Return to owner action queue" href="/media-actions" secondary /><Footer />
  </Screen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
