import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Platform, Pressable, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import * as Clipboard from 'expo-clipboard';
import { ActionButton, Feedback, Field, formStyles } from '../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../src/components/ui';
import { MEDIA_DRAFTS_KEY, mediaDraftReadiness, readMediaDrafts, type MediaDraft } from '../src/utils/mediaDrafts';
import { theme } from '../src/theme';
import { mediaProjectStatuses } from '../src/data/mediaProjects';

const priorities = ['All priorities', 'Needs attention', 'Stale records', 'Timing attention', 'Ready'] as const;
const sorts = ['Priority', 'Title', 'Status'] as const;

export default function MediaReadiness() {
  const router = useRouter(); const params = useLocalSearchParams<{ priority?: string | string[]; division?: string | string[]; status?: string | string[]; owner?: string | string[]; sort?: string | string[] }>();
  const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [ready, setReady] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [priority, setPriority] = useState<(typeof priorities)[number]>('All priorities'); const [division, setDivision] = useState('All divisions'); const [status, setStatus] = useState('All statuses'); const [owner, setOwner] = useState(''); const [sort, setSort] = useState<(typeof sorts)[number]>('Priority');
  useEffect(() => { void AsyncStorage.getItem(MEDIA_DRAFTS_KEY).then(value => setDrafts(readMediaDrafts(value))).catch(() => setError('Private production drafts could not be read for this report.')).finally(() => setReady(true)); }, []);
  const divisions = ['All divisions', ...Array.from(new Set(drafts.map(draft => draft.division)))];
  useEffect(() => { setPriority(priorities.find(item => item === params.priority) ?? 'All priorities'); }, [params.priority]); useEffect(() => { setDivision(divisions.find(item => item === params.division) ?? 'All divisions'); }, [params.division, drafts.length]); useEffect(() => { setStatus(['All statuses', ...mediaProjectStatuses].find(item => item === params.status) ?? 'All statuses'); }, [params.status]); useEffect(() => { setOwner(typeof params.owner === 'string' ? params.owner.slice(0, 120) : ''); }, [params.owner]); useEffect(() => { setSort(sorts.find(item => item === params.sort) ?? 'Priority'); }, [params.sort]);
  const rows = drafts.map(draft => ({ draft, readiness: mediaDraftReadiness(draft) })); const blocked = rows.filter(row => row.readiness.blocked).length; const stale = rows.filter(row => row.readiness.gates.some(gate => gate.recordQuality.state === 'stale')).length; const timing = rows.filter(row => row.readiness.timing.state === 'missing' || row.readiness.timing.state === 'overdue').length;
  const visible = rows.filter(row => (division === 'All divisions' || row.draft.division === division) && (status === 'All statuses' || row.draft.status === status) && (!owner.trim() || row.draft.owner.toLowerCase().includes(owner.trim().toLowerCase())) && matchesPriority(row, priority)).sort((a, b) => sort === 'Title' ? a.draft.title.localeCompare(b.draft.title) : sort === 'Status' ? a.draft.status.localeCompare(b.draft.status) || a.draft.title.localeCompare(b.draft.title) : priorityScore(a) - priorityScore(b) || a.draft.title.localeCompare(b.draft.title));
  const summary = ['PTOWN MEDIA GROUP — PRIVATE READINESS REPORT', '', `Private drafts: ${drafts.length}`, `Visible after filters: ${visible.length}`, `Blocked by planning gates or record quality: ${blocked}`, `Drafts with stale record references: ${stale}`, `Missing or passed timing: ${timing}`, '', ...visible.flatMap(({ draft, readiness }) => [`${draft.title} — ${draft.status}`, `Owner: ${draft.owner}`, `Timing: ${readiness.timing.label}`, `Readiness: ${readiness.blocked ? 'Needs attention' : 'Planning gates marked and references current'}`, `Next: ${readiness.recommendation ? readiness.recommendation.title : 'Authorized verification'}`, '']), 'PRIVATE DEVICE REPORT — Not an official approval, assignment, or production authorization.'].join('\n');
  async function copy() { setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(summary); } else if (!await Clipboard.setStringAsync(summary)) throw new Error(); setMessage('Private readiness report copied. It is not an official approval or authorization.'); } catch { setError('Copy is unavailable. Select the report and copy it manually.'); } }
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · OWNER READINESS VIEW" title="See what needs attention before anything advances." description="Review private production drafts across planning gates, record quality, timing, status, ownership, and recommended next action." /><PreviewNotice />
    <Card title="Private planning report" description="This device-only report reads private drafts stored here. It does not verify records, notify staff, assign work, change status, approve content, or authorize production." />
    {!ready ? <Body>Preparing private readiness report…</Body> : !drafts.length ? <Card title="No private drafts to report" description="Create a private production draft first. Sample dashboard projects are not included in this owner view." /> : <><View style={styles.grid}><Metric title="Private drafts" value={drafts.length} /><Metric title="Need attention" value={blocked} /><Metric title="Stale references" value={stale} /><Metric title="Timing attention" value={timing} /></View>
      <SectionHeader title="Filter and sort owner report" /><Text style={styles.cardTitle}>Priority</Text><ChoiceList label="Readiness priority" items={priorities} selected={priority} onChoose={value => { setPriority(value as typeof priority); router.setParams({ priority: value === 'All priorities' ? undefined : value }); }} />
      <Text style={styles.cardTitle}>Division</Text><ChoiceList label="Readiness division" items={divisions} selected={division} onChoose={value => { setDivision(value); router.setParams({ division: value === 'All divisions' ? undefined : value }); }} />
      <Text style={styles.cardTitle}>Status</Text><ChoiceList label="Readiness status" items={['All statuses', ...mediaProjectStatuses]} selected={status} onChoose={value => { setStatus(value); router.setParams({ status: value === 'All statuses' ? undefined : value }); }} />
      <Field label="Responsible role contains" value={owner} onChangeText={value => { const next = value.slice(0, 120); setOwner(next); router.setParams({ owner: next || undefined }); }} placeholder="Filter by owner or responsible role" />
      <Text style={styles.cardTitle}>Sort</Text><ChoiceList label="Readiness sort" items={sorts} selected={sort} onChoose={value => { setSort(value as typeof sort); router.setParams({ sort: value === 'Priority' ? undefined : value }); }} />
      {(priority !== 'All priorities' || division !== 'All divisions' || status !== 'All statuses' || owner || sort !== 'Priority') && <ActionButton label="Reset readiness filters" secondary onPress={() => { setPriority('All priorities'); setDivision('All divisions'); setStatus('All statuses'); setOwner(''); setSort('Priority'); router.setParams({ priority: undefined, division: undefined, status: undefined, owner: undefined, sort: undefined }); }} />}
      <SectionHeader title="Draft readiness" /><Text accessibilityLiveRegion="polite" style={styles.smallBody}>{visible.length} of {rows.length} private drafts shown</Text>{visible.length ? visible.map(({ draft, readiness }) => <View key={draft.id} style={styles.card}><Text style={{ color: readiness.blocked ? '#E8AAA2' : theme.colors.green, fontSize: 12, fontWeight: '700' }}>{readiness.blocked ? 'NEEDS ATTENTION' : 'PLANNING GATES MARKED'}</Text><Text style={styles.cardTitle}>{draft.title}</Text><Body>{draft.status} · {draft.division}{'\n'}Owner: {draft.owner}{'\n'}Timing: {readiness.timing.label}{'\n'}Record-quality issues: {readiness.recordIssues}{'\n'}Recommended next action: {readiness.recommendation?.title ?? 'Authorized verification of supporting records'}</Body><Button label={`Create follow-up for ${draft.title}`} href={{ pathname: '/media-actions', params: { draft: draft.id } }} /><Button label={`Review ${draft.title}`} href={{ pathname: '/media-drafts/[id]', params: { id: draft.id } }} secondary /></View>) : <Card title="No private drafts match" description="Choose another filter or reset the owner readiness report." />}
      <SectionHeader title="Copy owner report" /><Field label="Private readiness report" value={summary} multiline editable={false} style={{ minHeight: 340, textAlignVertical: 'top', lineHeight: 22 }} /><ActionButton label="Copy private readiness report" onPress={() => { void copy(); }} /></>}
    <Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}<Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer />
  </Screen>;
}
function Metric({ title, value }: { title: string; value: number }) { return <View style={[styles.card, { minWidth: 180, flexGrow: 1 }]}><Text style={{ color: theme.colors.gold, fontSize: 30, fontWeight: '700' }}>{value}</Text><Text style={styles.cardTitle}>{title}</Text></View>; }
function ChoiceList({ label, items, selected, onChoose }: { label: string; items: readonly string[]; selected: string; onChoose: (value: string) => void }) { return <View accessibilityRole="tablist" accessibilityLabel={label} style={styles.grid}>{items.map(item => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: selected === item }} onPress={() => onChoose(item)} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected === item ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected === item ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{item}</Text></Pressable>)}</View>; }
function matchesPriority(row: { readiness: ReturnType<typeof mediaDraftReadiness> }, priority: (typeof priorities)[number]) { const stale = row.readiness.gates.some(gate => gate.recordQuality.state === 'stale'); const timing = row.readiness.timing.state === 'missing' || row.readiness.timing.state === 'overdue'; if (priority === 'Needs attention') return row.readiness.blocked; if (priority === 'Stale records') return stale; if (priority === 'Timing attention') return timing; if (priority === 'Ready') return !row.readiness.blocked; return true; }
function priorityScore(row: { readiness: ReturnType<typeof mediaDraftReadiness> }) { if (row.readiness.timing.state === 'overdue') return 0; if (row.readiness.gates.some(gate => gate.recordQuality.state === 'stale')) return 1; if (row.readiness.blocked) return 2; if (row.readiness.timing.state === 'missing') return 3; return 4; }
