import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import { ActionButton, Feedback, formStyles } from '../../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader, styles } from '../../src/components/ui';
import { MEDIA_ACTIONS_KEY, readMediaActions, type MediaAction } from '../../src/utils/mediaActions';
import { MEDIA_DRAFTS_KEY, readMediaDrafts, type MediaDraft } from '../../src/utils/mediaDrafts';
import { theme } from '../../src/theme';

type Choice = 'preserve' | 'reassign' | 'remove';
export default function MediaDraftDelete() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const [drafts, setDrafts] = useState<MediaDraft[]>([]); const [actions, setActions] = useState<MediaAction[]>([]); const [choice, setChoice] = useState<Choice>('preserve'); const [target, setTarget] = useState(''); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([AsyncStorage.getItem(MEDIA_DRAFTS_KEY), AsyncStorage.getItem(MEDIA_ACTIONS_KEY)]).then(([draftValue, actionValue]) => { setDrafts(readMediaDrafts(draftValue)); setActions(readMediaActions(actionValue)); }).catch(() => setError('Deletion impact could not be reviewed on this device.')).finally(() => setReady(true)); }, []);
  const draft = drafts.find(item => item.id === id); const linked = actions.filter(item => item.draftId === id); const alternatives = drafts.filter(item => item.id !== id);
  async function confirm() { if (!draft) return; if (choice === 'reassign' && !alternatives.some(item => item.id === target)) { setError('Choose another private production draft for the linked actions.'); return; } setBusy(true); setError(null); const remainingDrafts = drafts.filter(item => item.id !== id); let nextActions = actions; if (choice === 'remove') nextActions = actions.filter(item => item.draftId !== id); if (choice === 'reassign') { const destination = alternatives.find(item => item.id === target)!; nextActions = actions.map(item => item.draftId === id ? { ...item, draftId: destination.id, draftTitle: destination.title, updatedAt: new Date().toISOString() } : item); } try { await AsyncStorage.multiSet([[MEDIA_DRAFTS_KEY, JSON.stringify(remainingDrafts)], [MEDIA_ACTIONS_KEY, JSON.stringify(nextActions)]]); setMessage('Private production draft removed after impact review.'); router.replace('/media-drafts'); } catch { setError('Removal failed. The private draft and linked actions were kept.'); } finally { setBusy(false); } }
  if (!ready) return <Screen><Body>Reviewing deletion impact…</Body></Screen>;
  if (!draft) return <Screen><PageHeader eyebrow="PRIVATE DRAFT REMOVAL" title="Draft not found." description="The draft may already be removed or belong to another device." /><Button label="Manage private production drafts" href="/media-drafts" secondary /><Footer /></Screen>;
  return <Screen><PageHeader eyebrow="PTOWN MEDIA GROUP · DELETION IMPACT REVIEW" title={`Before removing ${draft.title}`} description="Choose what happens to linked private follow-up actions. The production draft, workbook, and supporting-record references will be removed from this device." /><PreviewNotice />
    <Card title={`${linked.length} linked private ${linked.length === 1 ? 'action' : 'actions'}`} description={`${linked.filter(item => !item.completed).length} open · ${linked.filter(item => item.completed).length} completed. Review the choices below before deleting the draft.`} />
    {linked.map(item => <View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.action}</Text><Body>{item.completed ? 'Completed' : 'Open'} · {item.priority} · {item.owner}</Body></View>)}
    <SectionHeader title="Linked-action decision" /><View accessibilityRole="radiogroup" accessibilityLabel="Linked action decision" style={styles.grid}><Option label="Preserve as unlinked history" selected={choice === 'preserve'} onPress={() => setChoice('preserve')} /><Option label="Reassign to another draft" selected={choice === 'reassign'} onPress={() => setChoice('reassign')} /><Option label="Remove linked actions" selected={choice === 'remove'} onPress={() => setChoice('remove')} /></View>
    {choice === 'preserve' && <Card title="Preserve history" description="Linked actions remain on this device with the removed draft’s title. They will no longer open a live draft review." />}
    {choice === 'remove' && <Card title="Remove linked actions" description="All linked open and completed follow-up items will be removed with the draft. This cannot be undone unless you have a prior backup." />}
    {choice === 'reassign' && <><Text style={styles.cardTitle}>Choose destination draft</Text><View accessibilityRole="radiogroup" accessibilityLabel="Reassignment destination" style={styles.grid}>{alternatives.map(item => <Option key={item.id} label={item.title} selected={target === item.id} onPress={() => setTarget(item.id)} />)}</View>{!alternatives.length && <Card title="No other private draft available" description="Create another draft before choosing reassignment, or preserve/remove the linked actions." />}</>}
    <ActionButton label="Remove draft with reviewed action decision" disabled={busy} onPress={() => { void confirm(); }} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}<Button label="Cancel and keep private draft" href="/media-drafts" secondary /><Footer />
  </Screen>;
}
function Option({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} aria-checked={selected} onPress={onPress} style={{ minHeight: 48, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 24, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: selected ? theme.colors.gold : theme.colors.surface }}><Text style={{ color: selected ? theme.colors.background : theme.colors.cream, fontWeight: '600' }}>{label}</Text></Pressable>; }
