import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Platform, Text } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../../src/components/forms';
import { Body, Button, Card, Footer, PageHeader, PreviewNotice, Screen, SectionHeader } from '../../src/components/ui';
import { ARTIST_PROSPECTS_KEY, artistProspectNextStep, artistProspectReadiness, artistProspectSummary, readArtistProspects, type ArtistProspect } from '../../src/utils/artistProspects';

export default function ArtistProspectReview() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [prospect, setProspect] = useState<ArtistProspect | null>(null); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void AsyncStorage.getItem(ARTIST_PROSPECTS_KEY).then(value => setProspect(readArtistProspects(value).find(item => item.id === id) ?? null)).catch(() => setError('The private prospect profile could not be read on this device.')).finally(() => setReady(true)); }, [id]);
  if (!ready) return <Screen><Body>Loading private prospect review…</Body></Screen>;
  if (!prospect) return <Screen><PageHeader eyebrow="PRIVATE PROSPECT REVIEW" title="Prospect profile not found." description="The profile may have been removed or belongs to another device." /><Button label="Manage private prospect profiles" href="/artist-prospects" secondary /><Footer /></Screen>;
  const readiness = artistProspectReadiness(prospect); const summary = artistProspectSummary(prospect);
  async function copy() { setBusy(true); setMessage(null); setError(null); try { if (Platform.OS === 'web') { if (typeof navigator.clipboard?.writeText !== 'function') throw new Error(); await navigator.clipboard.writeText(summary); } else if (!await Clipboard.setStringAsync(summary)) throw new Error(); setMessage('Private prospect review copied. Nothing was submitted or sent.'); } catch { setError('Copy is unavailable. Select the review summary and copy it manually.'); } finally { setBusy(false); } }
  return <Screen><PageHeader eyebrow="PTOWN ARTIST DEVELOPMENT · PRIVATE PROSPECT REVIEW" title={prospect.name} description="Review booking-readiness details and the owner’s next planning step. This page does not contact, book, promise, approve, or enroll anyone." /><PreviewNotice /><Card title={readiness.ready ? 'Planning details complete' : `${readiness.missing.length} readiness details missing`} description={readiness.ready ? 'The profile contains the basic owner-planning details. Its status remains private and is not approval or booking readiness.' : `Complete ${readiness.missing.join(', ')} before owner review.`} /><SectionHeader title="Private profile" /><Card title={`${prospect.track} · ${prospect.status}`} description={`Home market: ${prospect.market || 'Not entered'}\nPortfolio or work reference: ${prospect.portfolio || 'Not entered'}\nAvailability or timing: ${prospect.availability || 'Not entered'}\nOwner planning notes: ${prospect.notes || 'Not entered'}`} /><SectionHeader title="Recommended owner next step" /><Card title="Next planning decision" description={artistProspectNextStep(prospect)} /><Button label={`Create or manage follow-ups for ${prospect.name}`} href={{ pathname: '/artist-prospect-actions', params: { prospect: prospect.id } }} /><ActionButton label="Copy private prospect review" disabled={busy} onPress={() => { void copy(); }} /><Field label="Private prospect review summary" value={summary} multiline editable={false} style={{ minHeight: 260, textAlignVertical: 'top', fontSize: 12 }} /><Feedback message={message} />{error && <Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}<Button label="Manage private prospect profiles" href="/artist-prospects" secondary /><Button label="Return to Artist Development" href="/artist-development" secondary /><Footer /></Screen>;
}
