export const ARTIST_PROSPECTS_KEY = '@ptown/artist-prospects/v1';
export type ArtistProspectTrack = 'Performance' | 'Production' | 'Culinary';
export type ArtistProspectStatus = 'New lead' | 'Needs materials' | 'Ready for owner review';
export type ArtistProspect = { id: string; name: string; track: ArtistProspectTrack; market: string; portfolio: string; availability: string; notes: string; status: ArtistProspectStatus; updatedAt: string };
export function readArtistProspects(value: string | null): ArtistProspect[] {
  if (!value) return []; const parsed: unknown = JSON.parse(value); if (!Array.isArray(parsed)) throw new Error('Invalid prospects');
  return parsed.filter((item): item is ArtistProspect => Boolean(item && typeof item === 'object' && typeof (item as ArtistProspect).id === 'string' && typeof (item as ArtistProspect).name === 'string' && (item as ArtistProspect).name.length <= 120 && ['Performance', 'Production', 'Culinary'].includes((item as ArtistProspect).track) && typeof (item as ArtistProspect).market === 'string' && (item as ArtistProspect).market.length <= 120 && typeof (item as ArtistProspect).portfolio === 'string' && (item as ArtistProspect).portfolio.length <= 300 && typeof (item as ArtistProspect).availability === 'string' && (item as ArtistProspect).availability.length <= 160 && typeof (item as ArtistProspect).notes === 'string' && (item as ArtistProspect).notes.length <= 1000 && ['New lead', 'Needs materials', 'Ready for owner review'].includes((item as ArtistProspect).status) && typeof (item as ArtistProspect).updatedAt === 'string'));
}
export function artistProspectReadiness(item: ArtistProspect) { const missing = [['home market', item.market], ['portfolio or work reference', item.portfolio], ['availability or timing', item.availability]].filter(([, value]) => !value.trim()).map(([label]) => label); return { ready: missing.length === 0, missing }; }
export function artistProspectNextStep(item: ArtistProspect) { const readiness = artistProspectReadiness(item); if (readiness.missing.length) return `Complete ${readiness.missing.join(', ')} before owner review.`; if (item.status === 'New lead') return 'Review the public work reference and decide whether this prospect fits PTown’s development vision.'; if (item.status === 'Needs materials') return 'Identify the additional public materials needed before any authorized outreach is considered.'; return 'Owner review may decide whether a separate, authorized outreach plan should be prepared. No contact has been sent.'; }
export function artistProspectSummary(item: ArtistProspect) { const readiness = artistProspectReadiness(item); return ['PTOWN ARTIST DEVELOPMENT — PRIVATE PROSPECT REVIEW', '', `Prospect: ${item.name}`, `Track: ${item.track}`, `Private planning status: ${item.status}`, `Home market: ${item.market || 'Not entered'}`, `Portfolio or work reference: ${item.portfolio || 'Not entered'}`, `Availability or timing: ${item.availability || 'Not entered'}`, `Owner planning notes: ${item.notes || 'Not entered'}`, `Readiness: ${readiness.ready ? 'Planning details complete' : `Missing ${readiness.missing.join(', ')}`}`, `Recommended next step: ${artistProspectNextStep(item)}`, `Last updated: ${item.updatedAt}`, '', 'PRIVATE DEVICE PLANNING — Not submitted, contacted, booked, promised, or enrolled.'].join('\n'); }
