import { useState } from 'react';
import { StyleSheet,Text,View } from 'react-native';
import { ActionButton,Feedback,Field } from '../../src/components/forms';
import { Body,Button,PageHeader,Screen,SectionHeader } from '../../src/components/ui';
import { runtime,supabaseConfigured } from '../../src/config/environment';
import { getSupabaseClient } from '../../src/services/supabaseClient';
import { theme } from '../../src/theme';
export default function AccountRecovery(){const[email,setEmail]=useState('');const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState<string|null>(null);const redirect=runtime.apiUrl?`${runtime.apiUrl.replace(/\/$/,'')}/operations/staff-access`:undefined;async function reset(){const client=getSupabaseClient();if(!client)return;setBusy(true);const{error}=await client.auth.resetPasswordForEmail(email.trim(),redirect?{redirectTo:redirect}:undefined);setFeedback(error?error.message:'Password-reset instructions requested. Check the staff email account.');setBusy(false);}async function magic(){const client=getSupabaseClient();if(!client)return;setBusy(true);const{error}=await client.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,...(redirect?{emailRedirectTo:redirect}:{})}});setFeedback(error?error.message:'Secure sign-in link requested. Check the staff email account.');setBusy(false);}return <Screen><PageHeader eyebrow="STAFF ACCOUNT SUPPORT" title="Recover staff access" description="Request approved account recovery without exposing passwords or administrative keys."/>{!supabaseConfigured?<View style={s.blocked}><Text style={s.blockedTitle}>DEVELOPMENT PROJECT NOT CONNECTED</Text><Body>Recovery actions remain disabled until the Supabase project URL and publishable key are configured.</Body></View>:<><Field label="Staff email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><View style={s.actions}><ActionButton label="Send password reset" disabled={busy||!email.includes('@')} onPress={()=>{void reset();}}/><ActionButton label="Send passwordless link" secondary disabled={busy||!email.includes('@')} onPress={()=>{void magic();}}/></View></>}<Feedback message={feedback}/><SectionHeader title="Account safeguards"/><Rule title="NO AUTOMATIC STAFF CREATION">Passwordless sign-in cannot create a new user. Only an approved administrative process may create staff accounts.</Rule><Rule title="SERVER-CONTROLLED ROLES">Recovery cannot promote a Viewer or change any staff role.</Rule><Rule title="SAFE RESPONSES">Production messaging should avoid revealing whether an email belongs to a staff account.</Rule><Button label="Staff sign-in" href="/operations/staff-access"/><Button label="Production readiness" href="/operations/production-readiness" secondary/></Screen>}
function Rule({title,children}:{title:string;children:string}){return <View style={s.rule}><Text style={s.ruleTitle}>{title}</Text><Body>{children}</Body></View>};const s=StyleSheet.create({blocked:{backgroundColor:'#2E2018',borderWidth:1,borderColor:'#A96F45',borderRadius:16,padding:18,gap:7},blockedTitle:{color:'#E8B07E',fontSize:10,fontWeight:'900',letterSpacing:1.1},actions:{gap:12},rule:{backgroundColor:theme.colors.surface,borderRadius:14,padding:15,gap:6},ruleTitle:{color:theme.colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.1}});
