import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../../src/components/forms';
import { Body, Button, Card, PageHeader, Screen, SectionHeader } from '../../src/components/ui';
import { artistLeads } from '../../src/data/bookingOperations';
import { useOperationsStore } from '../../src/state/OperationsStore';
import { theme } from '../../src/theme';

const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);
const number=(value:string)=>Math.max(0,Number(value)||0);
export default function EconomicsScreen(){
 const{getArtist,saveEconomics,saveOffer,setOfferStatus,economics,offers,canEdit,canApprove,busy}=useOperationsStore(); const[artistId,setArtistId]=useState(artistLeads[0].id);const[eventDate,setEventDate]=useState('');const[capacity,setCapacity]=useState('260');const[ticketPrice,setTicketPrice]=useState('55');const[attendance,setAttendance]=useState('200');const[foodSpend,setFoodSpend]=useState('35');const[artistFee,setArtistFee]=useState('');const[production,setProduction]=useState('5000');const[marketing,setMarketing]=useState('2500');const[hospitality,setHospitality]=useState('1500');const[other,setOther]=useState('1000');const[deposit,setDeposit]=useState('50');const[setLength,setSetLength]=useState('75 minutes');const[travel,setTravel]=useState('To be negotiated');const[hospitalityTerms,setHospitalityTerms]=useState('Hospitality rider subject to PTown approval');const[productionTerms,setProductionTerms]=useState('Technical rider subject to venue production review');const[feedback,setFeedback]=useState<string|null>(null);
 const ticketRevenue=number(ticketPrice)*number(attendance);const foodRevenue=number(foodSpend)*number(attendance);const revenue=ticketRevenue+foodRevenue;const costs=number(artistFee)+number(production)+number(marketing)+number(hospitality)+number(other);const profit=revenue-costs;const margin=revenue?profit/revenue*100:0;const breakEven=number(ticketPrice)+number(foodSpend)>0?Math.ceil(costs/(number(ticketPrice)+number(foodSpend))):0;const valid=/^\d{4}-\d{2}-\d{2}$/.test(eventDate)&&number(artistFee)>0;
 async function saveWorksheet(){setFeedback(null);const ok=await saveEconomics({artistId,eventDate,capacity:number(capacity),ticketPrice:number(ticketPrice),expectedAttendance:number(attendance),foodSpendPerGuest:number(foodSpend),artistFee:number(artistFee),productionCost:number(production),marketingCost:number(marketing),hospitalityCost:number(hospitality),otherCost:number(other)});if(ok)setFeedback('Economics worksheet saved.');}
 async function createOffer(){setFeedback(null);const ok=await saveOffer({artistId,eventDate,guarantee:number(artistFee),depositPercent:number(deposit),setLength,travel,hospitality:hospitalityTerms,production:productionTerms});if(ok)setFeedback('Offer terms saved as a draft. Nothing has been sent.');}
 return <Screen><PageHeader eyebrow="BOOKING DECISION SUPPORT" title="Event economics" description="Test the business case before PTown authorizes an artist offer."/>
 <Text style={styles.label}>Artist</Text><View style={styles.choices}>{artistLeads.map(base=>{const artist=getArtist(base.id)??base;return <Pressable key={artist.id} onPress={()=>setArtistId(artist.id)} style={[styles.choice,artistId===artist.id&&styles.selected]}><Text style={[styles.choiceText,artistId===artist.id&&styles.selectedText]}>{artist.name}</Text></Pressable>})}</View>
 <Field label="Proposed event date" hint="YYYY-MM-DD" value={eventDate} onChangeText={setEventDate}/><SectionHeader title="Revenue assumptions"/><View style={styles.grid}><MoneyField label="Room capacity" value={capacity} setValue={setCapacity}/><MoneyField label="Expected attendance" value={attendance} setValue={setAttendance}/><MoneyField label="Ticket price" value={ticketPrice} setValue={setTicketPrice}/><MoneyField label="Food & beverage per guest" value={foodSpend} setValue={setFoodSpend}/></View>
 <SectionHeader title="Event costs"/><View style={styles.grid}><MoneyField label="Artist guarantee" value={artistFee} setValue={setArtistFee}/><MoneyField label="Production" value={production} setValue={setProduction}/><MoneyField label="Marketing" value={marketing} setValue={setMarketing}/><MoneyField label="Hospitality / travel" value={hospitality} setValue={setHospitality}/><MoneyField label="Other costs" value={other} setValue={setOther}/></View>
 <View style={styles.dashboard}><Metric label="Projected revenue" value={money(revenue)}/><Metric label="Total event costs" value={money(costs)}/><Metric label="Projected profit" value={money(profit)} good={profit>=0}/><Metric label="Operating margin" value={`${margin.toFixed(1)}%`} good={margin>=15}/><Metric label="Break-even attendance" value={`${breakEven} guests`} good={breakEven<=number(capacity)}/><Metric label="Capacity use" value={`${number(capacity)?(number(attendance)/number(capacity)*100).toFixed(0):0}%`}/></View>
 {breakEven>number(capacity)&&<View style={styles.warning}><Text style={styles.warningTitle}>DO NOT ADVANCE YET</Text><Body>Break-even attendance exceeds the planned capacity. Revise the guarantee, pricing, sponsorship, or cost structure.</Body></View>}
 <ActionButton label={canEdit?'Save economics worksheet':'Viewer access · read only'} disabled={busy||!valid||!canEdit} onPress={()=>{void saveWorksheet();}}/><SectionHeader title="Offer terms"/><View style={styles.grid}><MoneyField label="Deposit percentage" value={deposit} setValue={setDeposit}/><Field label="Set length" value={setLength} onChangeText={setSetLength}/></View><Field label="Travel terms" value={travel} onChangeText={setTravel}/><Field label="Hospitality terms" value={hospitalityTerms} onChangeText={setHospitalityTerms} multiline/><Field label="Production terms" value={productionTerms} onChangeText={setProductionTerms} multiline/><ActionButton label="Save unsent offer draft" disabled={busy||!valid||!canEdit} onPress={()=>{void createOffer();}}/><Feedback message={feedback}/>
 <SectionHeader title="Offer approval queue"/>{offers.length?offers.map(offer=><View key={offer.id} style={styles.offer}><View style={{flex:1}}><Text style={styles.offerTitle}>{getArtist(offer.artistId)?.name} · {offer.eventDate}</Text><Text style={styles.offerMeta}>{money(offer.guarantee)} guarantee · {offer.depositPercent}% deposit · {offer.setLength}</Text></View><Text style={styles.badge}>{offer.status}</Text>{canEdit&&offer.status==='Draft'&&<ActionButton label="Submit" secondary onPress={()=>{void setOfferStatus(offer.id,'Pending approval');}}/>}{canApprove&&offer.status==='Pending approval'&&<ActionButton label="Approve" onPress={()=>{void setOfferStatus(offer.id,'Approved');}}/>}</View>):<Card title="No offer drafts" description="Complete the economics worksheet before preparing terms."/>}<Body>{economics.length} saved economics {economics.length===1?'worksheet':'worksheets'} on this device. Offers remain unsent.</Body><Button label="View audit history" href="/operations/audit" secondary/><Button label="Return to Booking Operations" href="/operations" secondary/></Screen>
}
function MoneyField({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return <View style={styles.field}><Field label={label} value={value} onChangeText={setValue} keyboardType="decimal-pad"/></View>};function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue,good!==undefined&&{color:good?theme.colors.green:'#E8AAA2'}]}>{value}</Text></View>}
const styles=StyleSheet.create({label:{color:theme.colors.cream,fontSize:15,fontWeight:'600'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{borderWidth:1,borderColor:theme.colors.border,borderRadius:20,paddingHorizontal:12,paddingVertical:9},selected:{backgroundColor:theme.colors.gold},choiceText:{color:theme.colors.cream,fontSize:12,fontWeight:'700'},selectedText:{color:theme.colors.background},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},field:{minWidth:'47%',flex:1},dashboard:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{backgroundColor:theme.colors.elevated,borderRadius:14,padding:14,minWidth:'47%',flex:1},metricLabel:{color:theme.colors.muted,fontSize:10},metricValue:{color:theme.colors.cream,fontSize:20,fontWeight:'900',marginTop:5},warning:{backgroundColor:'#2E2018',borderWidth:1,borderColor:'#A96F45',borderRadius:14,padding:14,gap:5},warningTitle:{color:'#E8B07E',fontSize:10,fontWeight:'900'},offer:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:16,padding:14,gap:10},offerTitle:{color:theme.colors.cream,fontSize:15,fontWeight:'800'},offerMeta:{color:theme.colors.muted,fontSize:11,marginTop:4},badge:{color:theme.colors.gold,fontSize:10,fontWeight:'900'}});
