import { useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActionButton, Feedback, Field, formStyles } from '../../src/components/forms';
import { Body, Button, Card, PageHeader, Screen, SectionHeader } from '../../src/components/ui';
import { artistLeads } from '../../src/data/bookingOperations';
import { useOperationsStore } from '../../src/state/OperationsStore';
import { theme } from '../../src/theme';

export default function OutreachScreen(){
 const params=useLocalSearchParams<{artistId?:string}>(); const{outreachDrafts,getArtist,saveOutreachDraft,setDraftStatus,removeOutreachDraft,busy,canEdit,canApprove,currentRole}=useOperationsStore();
 const initial=artistLeads.some(a=>a.id===params.artistId)?params.artistId!:artistLeads[0].id; const[artistId,setArtistId]=useState(initial); const[subject,setSubject]=useState('PTown Dinner Club booking inquiry'); const[message,setMessage]=useState(''); const[feedback,setFeedback]=useState<string|null>(null);
 async function save(){setFeedback(null);const ok=await saveOutreachDraft({artistId,subject:subject.trim(),message:message.trim()});if(ok){setMessage('');setFeedback('Outreach draft saved. It has not been sent.');}}
 return <Screen><PageHeader eyebrow="APPROVAL-GATED OUTREACH" title="Artist outreach drafts" description="Prepare professional inquiries, route them for approval, and keep every message unsent until PTown authorizes external communication."/>
 <View style={styles.access}><Text style={styles.accessRole}>{currentRole}</Text><Text style={styles.accessCopy}>{canApprove?'Draft and approval access':canEdit?'Draft and submit-for-approval access':'Read-only access'}</Text><Button label="Access roles" href="/operations/access" secondary /></View>
 {canEdit&&<><SectionHeader title="Create draft"/><Text style={styles.label}>Artist</Text><View style={styles.choices}>{artistLeads.map(base=>{const artist=getArtist(base.id)??base;return <Pressable key={artist.id} onPress={()=>setArtistId(artist.id)} style={[styles.choice,artistId===artist.id&&styles.choiceSelected]}><Text style={[styles.choiceText,artistId===artist.id&&styles.choiceTextSelected]}>{artist.name}</Text></Pressable>})}</View><Field label="Subject" value={subject} onChangeText={setSubject} maxLength={120}/><Field label="Message draft" hint="Draft only. Saving does not send this message." value={message} onChangeText={setMessage} multiline numberOfLines={8} maxLength={2000} style={{minHeight:180,textAlignVertical:'top'}}/><ActionButton label="Save unsent draft" disabled={busy||!subject.trim()||!message.trim()} onPress={()=>{void save();}}/><Feedback message={feedback}/></>}
 <SectionHeader title="Approval queue"/>{outreachDrafts.length?outreachDrafts.map(draft=><View key={draft.id} style={styles.draft}><View style={styles.draftHead}><View style={{flex:1}}><Text style={styles.artist}>{getArtist(draft.artistId)?.name??'Artist'}</Text><Text style={styles.subject}>{draft.subject}</Text></View><Text style={[styles.badge,draft.status==='Approved'&&styles.approved]}>{draft.status}</Text></View><Text style={styles.body}>{draft.message}</Text><Text style={styles.time}>Updated {new Date(draft.updatedAt).toLocaleString()}</Text>{canEdit&&<View style={formStyles.row}>{draft.status==='Draft'&&<ActionButton label="Submit for approval" secondary onPress={()=>{void setDraftStatus(draft.id,'Pending approval');}}/>}{canApprove&&draft.status==='Pending approval'&&<ActionButton label="Approve draft" onPress={()=>{void setDraftStatus(draft.id,'Approved');}}/>}<ActionButton label="Remove" secondary onPress={()=>{void removeOutreachDraft(draft.id);}}/></View>}{draft.status==='Approved'&&<Text style={styles.unsent}>APPROVED · STILL UNSENT</Text>}</View>):<Card title="No outreach drafts" description="Create a draft above. PTown will keep it unsent until it passes the approval workflow."/>}<Body>No email or message service is connected in this preview build.</Body><Button label="Return to Booking Operations" href="/operations" secondary /></Screen>
}
const styles=StyleSheet.create({access:{backgroundColor:theme.colors.elevated,borderRadius:14,padding:14,gap:8},accessRole:{color:theme.colors.gold,fontSize:15,fontWeight:'900'},accessCopy:{color:theme.colors.muted,fontSize:11},label:{color:theme.colors.cream,fontSize:15,fontWeight:'600'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{borderWidth:1,borderColor:theme.colors.border,borderRadius:20,paddingHorizontal:12,paddingVertical:9},choiceSelected:{backgroundColor:theme.colors.gold,borderColor:theme.colors.gold},choiceText:{color:theme.colors.cream,fontSize:12,fontWeight:'700'},choiceTextSelected:{color:theme.colors.background},draft:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:18,padding:18,gap:12},draftHead:{flexDirection:'row',gap:12,alignItems:'flex-start'},artist:{color:theme.colors.gold,fontSize:11,fontWeight:'900'},subject:{color:theme.colors.cream,fontSize:16,fontWeight:'800',marginTop:4},badge:{color:theme.colors.cream,borderWidth:1,borderColor:theme.colors.border,borderRadius:12,paddingHorizontal:8,paddingVertical:5,fontSize:9,fontWeight:'900'},approved:{borderColor:theme.colors.green,color:theme.colors.green},body:{color:theme.colors.muted,fontSize:13,lineHeight:20},time:{color:theme.colors.muted,fontSize:9},unsent:{color:theme.colors.green,fontSize:10,fontWeight:'900',letterSpacing:1.1}});
