import { StyleSheet,Text,View } from 'react-native';
import { Body,Button,Card,PageHeader,Screen,SectionHeader } from '../../src/components/ui';
import { productionChecks,runtime } from '../../src/config/environment';
import { useOperationsStore } from '../../src/state/OperationsStore';
import { theme } from '../../src/theme';

const securityChecks=[
 ['Authenticated staff accounts','Not connected','Replace preview role switching with verified identity and server-issued roles.'],
 ['Row-level authorization','Not connected','Enforce Owner, Booking Manager, and Viewer permissions on the server.'],
 ['Encrypted cloud database','Not connected','Move operations records from device-only storage to encrypted persistent storage.'],
 ['Conflict-safe synchronization','Contract ready','Use versioned records and reject stale writes for human review.'],
 ['Immutable audit identity','Not connected','Record authenticated user, server time, action, and before/after values.'],
 ['Backups and recovery','Not connected','Establish retention, restore testing, and incident recovery procedures.'],
] as const;
export default function ProductionReadiness(){const{auditLog,dueItems,bookings}=useOperationsStore();const configured=productionChecks.filter(x=>x.ready).length;return <Screen><PageHeader eyebrow="PRODUCTION FOUNDATION" title="Deployment readiness" description="A truthful control panel separating what works locally from what must be secured before staff rely on PTown Access in production."/><View style={s.banner}><Text style={s.mode}>{runtime.mode.toUpperCase()} MODE</Text><Text style={s.bannerTitle}>{runtime.syncEnabled?'Cloud sync configured':'Device-only preview storage'}</Text><Body>No operational record is represented as cloud-synced unless the production adapter and authentication settings are connected.</Body></View><SectionHeader title="Runtime configuration"/>{productionChecks.map(item=><View key={item.key} style={s.row}><View style={[s.dot,item.ready&&s.ready]}/><Text style={s.rowLabel}>{item.label}</Text><Text style={[s.status,item.ready&&s.statusReady]}>{item.ready?'READY':'NOT SET'}</Text></View>)}<Card title={`${configured}/${productionChecks.length} runtime checks ready`} description={configured===productionChecks.length?'Configuration is present; security and release verification are still required.':'Keep the app in preview mode until every production setting is verified.'}/><Button label="Supabase activation" href="/operations/activation"/><SectionHeader title="Security gates"/>{securityChecks.map(([title,status,description])=><View key={title} style={s.gate}><View style={s.gateHead}><Text style={s.gateTitle}>{title}</Text><Text style={s.status}>{status}</Text></View><Text style={s.description}>{description}</Text></View>)}<SectionHeader title="Local data awaiting migration"/><View style={s.metrics}><Metric label="Calendar records" value={bookings.length}/><Metric label="Due-date records" value={dueItems.length}/><Metric label="Audit events" value={auditLog.length}/></View><Button label="Create operations backup" href="/operations/backup"/><Button label="Open migration dry run" href="/operations/cloud-migration" secondary/><SectionHeader title="Required production sequence"/>{['Select and approve authentication/database provider','Create development and staging environments','Implement server-enforced role permissions','Migrate and validate local preview records','Run security, backup, conflict, and recovery tests','Complete iOS, Android, and web release review'].map((item,index)=><View key={item} style={s.step}><Text style={s.stepNumber}>{index+1}</Text><Text style={s.stepText}>{item}</Text></View>)}<Button label="Management command center" href="/operations/readiness"/><Button label="Booking Operations" href="/operations" secondary/></Screen>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>};const s=StyleSheet.create({banner:{backgroundColor:theme.colors.elevated,borderLeftWidth:3,borderLeftColor:theme.colors.gold,borderRadius:16,padding:18,gap:7},mode:{color:theme.colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5},bannerTitle:{color:theme.colors.cream,fontSize:19,fontWeight:'900'},row:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:13,padding:13,flexDirection:'row',alignItems:'center',gap:10},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#A96F45'},ready:{backgroundColor:theme.colors.green},rowLabel:{color:theme.colors.cream,fontSize:13,flex:1},status:{color:'#E8B07E',fontSize:9,fontWeight:'900'},statusReady:{color:theme.colors.green},gate:{backgroundColor:theme.colors.surface,borderRadius:15,padding:15,gap:7},gateHead:{flexDirection:'row',justifyContent:'space-between',gap:10},gateTitle:{color:theme.colors.cream,fontSize:14,fontWeight:'800'},description:{color:theme.colors.muted,fontSize:11,lineHeight:17},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{backgroundColor:theme.colors.surface,borderRadius:14,padding:14,minWidth:'30%',flex:1},metricValue:{color:theme.colors.gold,fontSize:22,fontWeight:'900'},metricLabel:{color:theme.colors.muted,fontSize:10,marginTop:4},step:{flexDirection:'row',gap:12,alignItems:'center',backgroundColor:theme.colors.surface,borderRadius:13,padding:13},stepNumber:{width:27,height:27,borderRadius:14,textAlign:'center',textAlignVertical:'center',backgroundColor:theme.colors.elevated,color:theme.colors.gold,fontWeight:'900'},stepText:{color:theme.colors.cream,fontSize:12,flex:1}});
