import { useEffect, useMemo, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { ActionButton, formStyles } from '../../src/components/forms';
import { Body, Button, Card, PageHeader, Screen, SectionHeader } from '../../src/components/ui';
import { supabaseConfigured } from '../../src/config/environment';
import type { StaffSession } from '../../src/services/operationsBackend';
import { reconcileOperations, type ReconciliationReport } from '../../src/services/operationsReconciliation';
import { getSupabaseClient } from '../../src/services/supabaseClient';
import { SupabaseOperationsBackend } from '../../src/services/supabaseOperationsBackend';
import { useOperationsStore } from '../../src/state/OperationsStore';
import { theme } from '../../src/theme';
import { buildOperationsMigrationPlan } from '../../src/utils/operationsMigration';

export default function Reconciliation(){
  const store=useOperationsStore();const plan=useMemo(()=>buildOperationsMigrationPlan(store),[store]);const[session,setSession]=useState<StaffSession|null>(null);const[checking,setChecking]=useState(false);const[report,setReport]=useState<ReconciliationReport|null>(null);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{let active=true;const client=getSupabaseClient();if(!client)return;new SupabaseOperationsBackend(client).getSession().then(value=>{if(active)setSession(value);});return()=>{active=false;};},[]);
  const allowed=supabaseConfigured&&session?.role==='Owner'&&plan.ready;
  async function run(){const client=getSupabaseClient();if(!client||!allowed)return;setChecking(true);setError(null);setReport(null);try{setReport(await reconcileOperations(plan,new SupabaseOperationsBackend(client)));}catch(cause){setError(cause instanceof Error?cause.message:'Cloud reconciliation failed.');}finally{setChecking(false);}}
  return <Screen>
    <PageHeader eyebrow="READ-ONLY INTEGRITY REVIEW" title="Cloud reconciliation" description="Compare every local operations record with the development project without changing either copy."/>
    <View style={s.banner}><Text style={s.bannerLabel}>NO-WRITE COMPARISON</Text><Text style={s.bannerTitle}>Keys and complete payloads are verified</Text><Body>Canonical checksums detect content differences even when JSON property order changes. This screen never uploads, overwrites, deletes, or restores records.</Body></View>
    <SectionHeader title="Comparison gate"/><Gate label="Supabase project configured" ready={supabaseConfigured}/><Gate label="Authenticated Owner" ready={session?.role==='Owner'}/><Gate label="Local records valid" ready={plan.ready}/>
    <ActionButton label={checking?'Comparing local and cloud records…':'Run read-only reconciliation'} disabled={!allowed||checking} onPress={()=>{void run();}}/>{error&&<Text accessibilityRole="alert" style={formStyles.error}>{error}</Text>}
    {!report?<Card title="No comparison run" description="Connect the development project and sign in as Owner to produce an integrity report."/>:<><View style={s.metrics}><Metric label="Local" value={report.localRecords}/><Metric label="Cloud" value={report.cloudRecords}/><Metric label="Matched" value={report.matched} good={report.clean}/><Metric label="Local only" value={report.localOnly} good={report.localOnly===0}/><Metric label="Cloud only" value={report.cloudOnly} good={report.cloudOnly===0}/><Metric label="Conflicts" value={report.contentConflicts} good={report.contentConflicts===0}/></View><Card title={report.clean?'Reconciliation passed':'Owner review required'} description={report.clean?'Every local record key and payload matches the development project.':`${report.issues.length} difference${report.issues.length===1?' requires':'s require'} review. No records were changed.`}/><SectionHeader title="Difference register"/>{report.issues.length?report.issues.slice(0,100).map(issue=><View key={`${issue.collection}-${issue.recordId}-${issue.kind}`} style={s.issue}><View style={{flex:1}}><Text style={s.issueTitle}>{issue.kind}</Text><Text style={s.issueKey}>{issue.collection} / {issue.recordId}</Text>{issue.localChecksum&&<Text style={s.hash}>Local {issue.localChecksum} · Cloud {issue.cloudChecksum}</Text>}</View></View>):<Body>No differences found.</Body>}<Body>Checked {new Date(report.checkedAt).toLocaleString()}. Reports are read-only and are not proof that backups or restore procedures have been tested.</Body></>}
    <Button label="Cloud migration" href="/operations/cloud-migration"/><Button label="Operations backup" href="/operations/backup" secondary/><Button label="Production readiness" href="/operations/production-readiness" secondary/>
  </Screen>;
}
function Gate({label,ready}:{label:string;ready:boolean}){return <View style={s.gate}><View style={[s.dot,ready&&s.ready]}/><Text style={s.gateLabel}>{label}</Text><Text style={[s.state,ready&&s.stateReady]}>{ready?'READY':'LOCKED'}</Text></View>}
function Metric({label,value,good}:{label:string;value:number;good?:boolean}){return <View style={s.metric}><Text style={[s.metricValue,good!==undefined&&{color:good?theme.colors.green:'#E8AAA2'}]}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
const s=StyleSheet.create({banner:{backgroundColor:theme.colors.elevated,borderLeftWidth:3,borderLeftColor:theme.colors.gold,borderRadius:16,padding:18,gap:7},bannerLabel:{color:theme.colors.gold,fontSize:10,fontWeight:'900',letterSpacing:1.5},bannerTitle:{color:theme.colors.cream,fontSize:19,fontWeight:'900'},gate:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:13,padding:13,flexDirection:'row',alignItems:'center',gap:10},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#A96F45'},ready:{backgroundColor:theme.colors.green},gateLabel:{color:theme.colors.cream,fontSize:13,flex:1},state:{color:'#E8B07E',fontSize:9,fontWeight:'900'},stateReady:{color:theme.colors.green},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{backgroundColor:theme.colors.surface,borderRadius:14,padding:14,minWidth:'30%',flex:1},metricValue:{color:theme.colors.gold,fontSize:22,fontWeight:'900'},metricLabel:{color:theme.colors.muted,fontSize:10,marginTop:4},issue:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:13,padding:14,flexDirection:'row'},issueTitle:{color:'#E8AAA2',fontSize:13,fontWeight:'800'},issueKey:{color:theme.colors.cream,fontSize:12,marginTop:4},hash:{color:theme.colors.muted,fontSize:9,marginTop:4}});
