import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useCallback, useContext, useEffect, useRef, useState, type PropsWithChildren } from 'react';
import { artistLeads, type ArtistLead, type PipelineStatus } from '../data/bookingOperations';

export const OPERATIONS_STORAGE_KEY = '@ptown/operations/v1';
export type ArtistUpdate = Pick<ArtistLead, 'status' | 'contactRoute' | 'contactVerified' | 'contactSource' | 'contactVerifiedOn' | 'lastContact' | 'followUpDate' | 'nextAction' | 'notes' | 'feeRange' | 'contractStatus' | 'paymentStatus'>;
export type BookingEntry = { id: string; artistId: string; date: string; program: string; status: 'Hold' | 'Inquiry' | 'Offer' | 'Contracted'; notes: string; createdAt: string };
export type OperationsRole = 'Owner' | 'Booking Manager' | 'Viewer';
export type OutreachDraft = { id: string; artistId: string; subject: string; message: string; status: 'Draft' | 'Pending approval' | 'Approved'; createdAt: string; updatedAt: string };
export type EconomicsWorksheet = { id: string; artistId: string; eventDate: string; capacity: number; ticketPrice: number; expectedAttendance: number; foodSpendPerGuest: number; sponsorOffset: number; artistFee: number; productionCost: number; marketingCost: number; hospitalityCost: number; otherCost: number; updatedAt: string };
export type OfferTerms = { id: string; artistId: string; eventDate: string; guarantee: number; depositPercent: number; setLength: string; travel: string; hospitality: string; production: string; status: 'Draft' | 'Pending approval' | 'Approved'; updatedAt: string };
export type AuditEntry = { id: string; action: string; detail: string; role: OperationsRole; createdAt: string };
export type DealRoomRecord = { artistId: string; technicalRider: string; hospitalityRider: string; travelPlan: string; checklist: Record<string, boolean>; updatedAt: string };
export type ShowDayRecord = { id: string; artistId: string; eventDate: string; venueLead: string; productionLead: string; hospitalityLead: string; securityLead: string; boxOfficeLead: string; loadIn: string; soundcheck: string; doors: string; showtime: string; curfew: string; completed: Record<string, boolean>; notes: string; updatedAt: string };
export type SettlementRecord = { id: string; artistId: string; eventDate: string; paidAttendance: number; compAttendance: number; ticketGross: number; foodBeverageGross: number; sponsorRevenue: number; refunds: number; taxesFees: number; artistPayment: number; productionCost: number; laborCost: number; marketingCost: number; hospitalityCost: number; otherCost: number; notes: string; updatedAt: string };
export type PostShowReview = { id: string; artistId: string; eventDate: string; attendanceScore: number; audienceScore: number; professionalismScore: number; productionScore: number; financialScore: number; recommendation: 'Rebook' | 'Rebook with conditions' | 'Do not rebook' | 'Review later'; notes: string; updatedAt: string };
export type IncidentRecord = { id: string; eventDate: string; area: 'Guest' | 'Artist' | 'Production' | 'Security' | 'Medical' | 'Facility'; severity: 'Low' | 'Moderate' | 'High' | 'Critical'; summary: string; response: string; followUp: string; resolved: boolean; createdAt: string };
export type DueItem = { id: string; title: string; category: 'Follow-up' | 'Contract' | 'Payment' | 'Document expiration' | 'Production' | 'Marketing'; dueDate: string; owner: string; completed: boolean; createdAt: string };
export type OperationsState = { version: 1; artistUpdates: Record<string, ArtistUpdate>; bookings: BookingEntry[]; currentRole: OperationsRole; outreachDrafts: OutreachDraft[]; economics: EconomicsWorksheet[]; offers: OfferTerms[]; auditLog: AuditEntry[]; dealRooms: Record<string, DealRoomRecord>; showDays: ShowDayRecord[]; settlements: SettlementRecord[]; postShowReviews: PostShowReview[]; incidents: IncidentRecord[]; dueItems: DueItem[] };
type Store = OperationsState & { ready: boolean; busy: boolean; error: string | null; canEdit: boolean; canApprove: boolean; getArtist: (id: string) => ArtistLead | undefined; restoreOperations: (backup: OperationsState) => Promise<boolean>; saveArtist: (id: string, update: ArtistUpdate) => Promise<boolean>; saveBooking: (booking: Omit<BookingEntry, 'id' | 'createdAt'>) => Promise<boolean>; removeBooking: (id: string) => Promise<boolean>; setRole: (role: OperationsRole) => Promise<boolean>; saveOutreachDraft: (draft: Omit<OutreachDraft, 'id' | 'createdAt' | 'updatedAt' | 'status'>) => Promise<boolean>; setDraftStatus: (id: string, status: OutreachDraft['status']) => Promise<boolean>; removeOutreachDraft: (id: string) => Promise<boolean>; saveEconomics: (worksheet: Omit<EconomicsWorksheet, 'id' | 'updatedAt'>) => Promise<boolean>; saveOffer: (offer: Omit<OfferTerms, 'id' | 'updatedAt' | 'status'>) => Promise<boolean>; setOfferStatus: (id: string, status: OfferTerms['status']) => Promise<boolean>; saveDealRoom: (record: Omit<DealRoomRecord, 'updatedAt'>) => Promise<boolean>; saveShowDay: (record: Omit<ShowDayRecord, 'id' | 'updatedAt'>) => Promise<boolean>; saveSettlement: (record: Omit<SettlementRecord, 'id' | 'updatedAt'>) => Promise<boolean>; savePostShowReview: (record: Omit<PostShowReview, 'id' | 'updatedAt'>) => Promise<boolean>; saveIncident: (record: Omit<IncidentRecord, 'id' | 'createdAt'>) => Promise<boolean>; resolveIncident: (id: string) => Promise<boolean>; saveDueItem: (record: Omit<DueItem, 'id' | 'createdAt' | 'completed'>) => Promise<boolean>; completeDueItem: (id: string) => Promise<boolean> };

const emptyState = (): OperationsState => ({ version: 1, artistUpdates: {}, bookings: [], currentRole: 'Owner', outreachDrafts: [], economics: [], offers: [], auditLog: [], dealRooms: {}, showDays: [], settlements: [], postShowReviews: [], incidents: [], dueItems: [] });
const audit = (state: OperationsState, action: string, detail: string): AuditEntry[] => [{ id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, action, detail, role:state.currentRole, createdAt:new Date().toISOString() }, ...state.auditLog].slice(0,200);
const Context = createContext<Store | null>(null);
const statuses: PipelineStatus[] = ['Identified','Contacted','Warm','Negotiating','Booked','Nurture'];
const contractStatuses: ArtistLead['contractStatus'][] = ['Not started','Drafting','Sent','Signed'];
const paymentStatuses: ArtistLead['paymentStatus'][] = ['Not started','Deposit due','Deposit paid','Paid in full'];

export function parseOperationsState(raw: string | null): OperationsState {
  if (!raw) return emptyState();
  const value = JSON.parse(raw);
  if (!value || value.version !== 1 || typeof value.artistUpdates !== 'object' || !Array.isArray(value.bookings)) throw new Error('Invalid operations data');
  const artistUpdates: Record<string, ArtistUpdate> = {};
  for (const [id, update] of Object.entries(value.artistUpdates as Record<string, ArtistUpdate>)) {
    if (!artistLeads.some(artist => artist.id === id) || !statuses.includes(update.status) || !contractStatuses.includes(update.contractStatus) || !paymentStatuses.includes(update.paymentStatus)) continue;
    artistUpdates[id] = update;
  }
  const bookings = value.bookings.filter((item: BookingEntry) => item && typeof item.id === 'string' && artistLeads.some(artist => artist.id === item.artistId) && /^\d{4}-\d{2}-\d{2}$/.test(item.date) && ['Hold','Inquiry','Offer','Contracted'].includes(item.status));
  const currentRole: OperationsRole = ['Owner','Booking Manager','Viewer'].includes(value.currentRole) ? value.currentRole : 'Owner';
  const outreachDrafts = Array.isArray(value.outreachDrafts) ? value.outreachDrafts.filter((draft: OutreachDraft) => draft && typeof draft.id === 'string' && artistLeads.some(artist => artist.id === draft.artistId) && ['Draft','Pending approval','Approved'].includes(draft.status)) : [];
  const economics = Array.isArray(value.economics) ? value.economics.map((item: EconomicsWorksheet) => ({...item,sponsorOffset:Number(item.sponsorOffset)||0})) : [];
  const offers = Array.isArray(value.offers) ? value.offers : [];
  const auditLog = Array.isArray(value.auditLog) ? value.auditLog : [];
  const dealRooms = value.dealRooms && typeof value.dealRooms === 'object' ? value.dealRooms : {};
  const showDays = Array.isArray(value.showDays) ? value.showDays : [];
  const settlements = Array.isArray(value.settlements) ? value.settlements : [];
  const postShowReviews = Array.isArray(value.postShowReviews) ? value.postShowReviews : [];
  const incidents = Array.isArray(value.incidents) ? value.incidents : [];
  const dueItems = Array.isArray(value.dueItems) ? value.dueItems : [];
  return { version: 1, artistUpdates, bookings, currentRole, outreachDrafts, economics, offers, auditLog, dealRooms, showDays, settlements, postShowReviews, incidents, dueItems };
}

export function OperationsStoreProvider({ children }: PropsWithChildren) {
  const [state, setState] = useState<OperationsState>(emptyState);
  const stateRef = useRef(state);
  const [ready, setReady] = useState(false);
  const [pending, setPending] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const queue = useRef<Promise<unknown>>(Promise.resolve());
  useEffect(() => { let active = true; AsyncStorage.getItem(OPERATIONS_STORAGE_KEY).then(raw => { const loaded = parseOperationsState(raw); if (!active) return; stateRef.current = loaded; setState(loaded); setReady(true); }).catch(() => { if (active) setError('Booking operations data could not be read on this device.'); }); return () => { active = false; }; }, []);
  const update = useCallback((change: (current: OperationsState) => OperationsState) => {
    setPending(count => count + 1);
    const operation = queue.current.then(async () => { try { const next = change(stateRef.current); await AsyncStorage.setItem(OPERATIONS_STORAGE_KEY, JSON.stringify(next)); stateRef.current = next; setState(next); setReady(true); setError(null); return true; } catch { setError('This device could not save the operations update.'); return false; } finally { setPending(count => count - 1); } });
    queue.current = operation; return operation;
  }, []);
  const getArtist = useCallback((id: string) => { const base = artistLeads.find(artist => artist.id === id); return base ? { ...base, ...state.artistUpdates[id] } : undefined; }, [state.artistUpdates]);
  const restoreOperations = useCallback((backup: OperationsState) => { const validated=parseOperationsState(JSON.stringify(backup)); return update(() => validated); }, [update]);
  const canEdit = state.currentRole !== 'Viewer'; const canApprove = state.currentRole === 'Owner';
  const saveArtist = useCallback((id: string, artistUpdate: ArtistUpdate) => stateRef.current.currentRole !== 'Viewer' && artistLeads.some(artist => artist.id === id) ? update(current => ({ ...current, artistUpdates: { ...current.artistUpdates, [id]: artistUpdate }, auditLog:audit(current,'Artist CRM updated',artistLeads.find(a=>a.id===id)?.name??id) })) : Promise.resolve(false), [update]);
  const saveBooking = useCallback((booking: Omit<BookingEntry, 'id' | 'createdAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current => ({ ...current, bookings: [...current.bookings, { ...booking, id: `booking-${Date.now()}`, createdAt: new Date().toISOString() }], auditLog:audit(current,'Calendar entry added',`${booking.date} · ${booking.program}`) })) : Promise.resolve(false), [update]);
  const removeBooking = useCallback((id: string) => stateRef.current.currentRole !== 'Viewer' ? update(current => ({ ...current, bookings: current.bookings.filter(booking => booking.id !== id), auditLog:audit(current,'Calendar entry removed',id) })) : Promise.resolve(false), [update]);
  const setRole = useCallback((currentRole: OperationsRole) => update(current => ({ ...current, currentRole, auditLog:audit(current,'Preview role changed',`${current.currentRole} → ${currentRole}`) })), [update]);
  const saveOutreachDraft = useCallback((draft: Omit<OutreachDraft, 'id' | 'createdAt' | 'updatedAt' | 'status'>) => stateRef.current.currentRole !== 'Viewer' ? update(current => { const now = new Date().toISOString(); return { ...current, outreachDrafts: [...current.outreachDrafts, { ...draft, id:`outreach-${Date.now()}`, status:'Draft', createdAt:now, updatedAt:now }], auditLog:audit(current,'Outreach draft created',draft.subject) }; }) : Promise.resolve(false), [update]);
  const setDraftStatus = useCallback((id: string, status: OutreachDraft['status']) => update(current => { if (status === 'Approved' && current.currentRole !== 'Owner') return current; if (current.currentRole === 'Viewer') return current; return { ...current, outreachDrafts: current.outreachDrafts.map(draft => draft.id === id ? { ...draft, status, updatedAt:new Date().toISOString() } : draft), auditLog:audit(current,'Outreach status changed',`${id} → ${status}`) }; }), [update]);
  const removeOutreachDraft = useCallback((id: string) => stateRef.current.currentRole !== 'Viewer' ? update(current => ({ ...current, outreachDrafts: current.outreachDrafts.filter(draft => draft.id !== id) })) : Promise.resolve(false), [update]);
  const saveEconomics = useCallback((worksheet: Omit<EconomicsWorksheet, 'id' | 'updatedAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current => { const item={...worksheet,id:`economics-${Date.now()}`,updatedAt:new Date().toISOString()}; return {...current,economics:[item,...current.economics],auditLog:audit(current,'Economics worksheet saved',`${worksheet.eventDate} · ${artistLeads.find(a=>a.id===worksheet.artistId)?.name??worksheet.artistId}`)}; }) : Promise.resolve(false),[update]);
  const saveOffer = useCallback((offer: Omit<OfferTerms, 'id' | 'updatedAt' | 'status'>) => stateRef.current.currentRole !== 'Viewer' ? update(current => { const item={...offer,id:`offer-${Date.now()}`,status:'Draft' as const,updatedAt:new Date().toISOString()}; return {...current,offers:[item,...current.offers],auditLog:audit(current,'Offer terms drafted',`${offer.eventDate} · $${offer.guarantee}`)}; }) : Promise.resolve(false),[update]);
  const setOfferStatus = useCallback((id:string,status:OfferTerms['status']) => update(current=>{if(current.currentRole==='Viewer'||(status==='Approved'&&current.currentRole!=='Owner'))return current;return{...current,offers:current.offers.map(offer=>offer.id===id?{...offer,status,updatedAt:new Date().toISOString()}:offer),auditLog:audit(current,'Offer status changed',`${id} → ${status}`)};}),[update]);
  const saveDealRoom = useCallback((record: Omit<DealRoomRecord,'updatedAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const item={...record,updatedAt:new Date().toISOString()};return{...current,dealRooms:{...current.dealRooms,[record.artistId]:item},auditLog:audit(current,'Booking deal room updated',artistLeads.find(a=>a.id===record.artistId)?.name??record.artistId)};}) : Promise.resolve(false),[update]);
  const saveShowDay = useCallback((record: Omit<ShowDayRecord,'id'|'updatedAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const existing=current.showDays.find(item=>item.artistId===record.artistId&&item.eventDate===record.eventDate);const item={...record,id:existing?.id??`showday-${Date.now()}`,updatedAt:new Date().toISOString()};return{...current,showDays:[item,...current.showDays.filter(entry=>entry.id!==existing?.id)],auditLog:audit(current,'Show-day advance saved',`${record.eventDate} · ${artistLeads.find(a=>a.id===record.artistId)?.name??record.artistId}`)};}) : Promise.resolve(false),[update]);
  const saveSettlement = useCallback((record: Omit<SettlementRecord,'id'|'updatedAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const existing=current.settlements.find(item=>item.artistId===record.artistId&&item.eventDate===record.eventDate);const item={...record,id:existing?.id??`settlement-${Date.now()}`,updatedAt:new Date().toISOString()};return{...current,settlements:[item,...current.settlements.filter(entry=>entry.id!==existing?.id)],auditLog:audit(current,'Event settlement saved',`${record.eventDate} · ${artistLeads.find(a=>a.id===record.artistId)?.name??record.artistId}`)};}) : Promise.resolve(false),[update]);
  const savePostShowReview = useCallback((record: Omit<PostShowReview,'id'|'updatedAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const existing=current.postShowReviews.find(item=>item.artistId===record.artistId&&item.eventDate===record.eventDate);const item={...record,id:existing?.id??`review-${Date.now()}`,updatedAt:new Date().toISOString()};return{...current,postShowReviews:[item,...current.postShowReviews.filter(entry=>entry.id!==existing?.id)],auditLog:audit(current,'Post-show review saved',`${record.eventDate} · ${record.recommendation}`)};}) : Promise.resolve(false),[update]);
  const saveIncident = useCallback((record: Omit<IncidentRecord,'id'|'createdAt'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const item={...record,id:`incident-${Date.now()}`,createdAt:new Date().toISOString()};return{...current,incidents:[item,...current.incidents],auditLog:audit(current,'Incident logged',`${record.severity} · ${record.area}`)};}) : Promise.resolve(false),[update]);
  const resolveIncident = useCallback((id:string) => stateRef.current.currentRole !== 'Viewer' ? update(current=>({...current,incidents:current.incidents.map(item=>item.id===id?{...item,resolved:true}:item),auditLog:audit(current,'Incident resolved',id)})) : Promise.resolve(false),[update]);
  const saveDueItem = useCallback((record: Omit<DueItem,'id'|'createdAt'|'completed'>) => stateRef.current.currentRole !== 'Viewer' ? update(current=>{const item={...record,id:`due-${Date.now()}`,completed:false,createdAt:new Date().toISOString()};return{...current,dueItems:[item,...current.dueItems],auditLog:audit(current,'Management due date added',`${record.dueDate} · ${record.title}`)};}) : Promise.resolve(false),[update]);
  const completeDueItem = useCallback((id:string) => stateRef.current.currentRole !== 'Viewer' ? update(current=>({...current,dueItems:current.dueItems.map(item=>item.id===id?{...item,completed:true}:item),auditLog:audit(current,'Management task completed',id)})) : Promise.resolve(false),[update]);
  return <Context.Provider value={{ ...state, ready, busy: pending > 0, error, canEdit, canApprove, getArtist, restoreOperations, saveArtist, saveBooking, removeBooking, setRole, saveOutreachDraft, setDraftStatus, removeOutreachDraft, saveEconomics, saveOffer, setOfferStatus, saveDealRoom, saveShowDay, saveSettlement, savePostShowReview, saveIncident, resolveIncident, saveDueItem, completeDueItem }}>{children}</Context.Provider>;
}

export function useOperationsStore() { const store = useContext(Context); if (!store) throw new Error('OperationsStoreProvider is required'); return store; }
